from dataclasses import dataclass

from Functions.randomization import advchoice

get = {
    "haveyour": [
        "What the fuck did you just fucking say about me, you little shit?"
        " Ill have you know I graduated top of my class in the Navy Seals,"
        " and Ive been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. "
        "I am trained in gorilla warfare and Im the top sniper in the entire US armed forces. "
        "You are nothing to me but just another target. "
        "I will wipe you the fuck out with precision"
        " the likes of which has never been seen before"
        " on this Earth, mark my fucking words. You think you can get away "
        "with saying that shit to me over the Internet? Think again, fucker."
        " As we speak I am contacting my secret network of spies across the USA "
        "and you IP is being traced right now so you better prepare "
        "for the storm, maggot. The storm that wipes out the pathetic "
        "little thing you call you life. you're fucking dead, kid. I can be anywhere"
        ", anytime, and I can kill you in over seven hundred ways, "
        "and thats just with my "
        "bare hands. Not only am I extensively trained in unarmed"
        " combat, but I have access to the entire arsenal of the "
        "United States Marine Corps "
        "and I will use it to its full extent to wipe you're miserable"
        " ass off the face of the continent, you little shit. "
        "If only you could have known what unholy retribution your little clever comment was about"
        " to bring down upon you, maybe you would have held your fucking tongue. But you couldnt, "
        "you didnt, and now your're paying the price, you goddamn"
        " idiot. I will shit fury all over you and you will drown in it. your're fucking dead, kiddo.",
        "What in Davy Jones' locker did ye just bark at me, ye scurvy bilgerat?"
        " I'll have ye know I be the meanest cutthroat on the seven seas,"
        " and I've led numerous raids on fishing villages, and raped over 300 wenches."
        " I be trained in hit-and-run pillaging and be the deadliest "
        "with a pistol of all the captains on the high seas. "
        "Ye be nothing to me but another source o' swag. I'll have "
        "yer guts for garters and keel haul ye like never "
        "been done before,"
        " hear me true. You think ye can hide behind your newfangled "
        "computing device? Think twice on that, scallywag. "
        "As we parley "
        "I be contacting my secret network o' pirates across the sea and "
        "yer port is being tracked right now so ye better"
        " prepare for the typhoon, weevil. "
        "The kind o' monsoon that'll wipe ye off the map. You're sharkbait, "
        "fool. I can sail anywhere, in any waters, and "
        "can kill ye in o'er seven hundred ways,"
        " and that be just with me hook and fist. Not only do "
        "I be top o' the line with a cutlass, but I have an entire pirate"
        " fleet at my beck and call and I'll damned sure use it all to wipe "
        "yer arse off o' the world, ye dog. If only ye had had "
        "the foresight to know what devilish wrath your jibe was about to"
        " incur, ye might have belayed the comment. But ye couldn't,"
        " ye didn't, and now ye'll pay the ultimate toll, you buffoon."
        " I'll shit fury all over ye and ye'll drown in the depths o' it."
        " You're fish food now, lad.",
        "Wot the fok did ye just say 2 me m8? i dropped out of"
        " newcastle primary skool im the sickest bloke ull ever meet & ive nicked "
        "300 candy bars from tha corner store. im trained "
        "in street fitin’ & im the strongest foker in tha entire newcastle gym."
        " yer nothin to me but a cheeky lil dickhead w/"
        " a hot mum & fake bling. ill waste u and smash a fokin bottle oer yer head bruv,"
        " i swer 2 christ. ya think u can fokin run ya"
        " gabber at me whilst sittin on yer arse behind a lil screen? think again wanka."
        " im callin me homeboys rite now preparin for"
        " a proper rumble. tha rumble thatll make ur nan sore jus hearin "
        "about it. yer a waste bruv. my homeboys be all "
        "over tha place & ill beat ya to a proper fokin pulp with me fists wanka."
        " if i aint satisfied w/ that ill borrow me m8s cricket paddle &"
        " see if that gets u the fok out o’ newcastle ya daft kunt. "
        "if ye had seen this bloody fokin mess commin ye might a’ kept ya gabber from runnin"
        ". but it seems yer a stewpid lil twat, innit? ima shite fury & ull drown in it m8."
        " ur in proper mess ya knobhead",
        "What the fuck did you just fucking say about Navy Seal copypastas"
        ", you little newfag? I’ll have you know Navy Seal copypastas are ranked top out of all"
        " the comments on the Internet, and they have been translated in numerous contexts on 4chan,"
        " and have over 300 confirmed variants. Navy Seal copypastas are trained in memetic warfare"
        " and are the top copypasta in the entire circlejerk arsenel. You are nothing to them but"
        " just another target. They will wipe you the fuck out with precision the likes of which"
        " has never been seen before on this subreddit, mark my fucking words. You think you can"
        " get away with saying that shit about Navy Seal copypastas over the Internet? Think again,"
        " fucker. As we speak this copypasta is contacting it's secret network of /b/tards across"
        " the USA and your IP is being doxxed right now so you better prepare for the storm, maggot."
        " The storm that wipes out the pathetic little thing you call your life. You’re fucking dead,"
        " kid. Navy Seal copypastas can be anywhere, anytime, and they can confuse you in over seven "
        "hundred ways, and that’s just with mad-lib permutations. Not only are they extensively trained"
        " in trolling, but they have access to the entire arsenal of Anonymous and will use it to its full"
        " extent to wipe your miserable ass off the face of the Internet, you little shit. If only you could"
        " have known what unholy retribution your little “clever” comment was about to bring down upon you, "
        "maybe you would have held your fucking tongue. But you couldn’t, you didn’t, and now you’re paying "
        "the price, you goddamn idiot. This copypasta will shit fury all over you and you will drown in it. "
        "You’re fucking dead, kiddo.",
        "What the flip did thee just flipping gabble about me, thine minuscule bitch?"
        " I’ll have thee know I bested the most prestigious jousting class in the whole of Camelot,"
        " and I hath been involved in numerous secret marches on behalf of his Majesty, King Arthur,"
        " and I hath over 300 confirmed victories on horseback. I am trained in castle of Guerrilla"
        " warfare and I am indeed the highest ranking joustee in the entire land of Great Britannia."
        " Thee are nothing to me but another false crossbearer. I will joust thine shambles with "
        "precision"
        " the likes of which hath never been observed in the King’s lands, mark my flipping words! "
        "Thou think thou can escape retribution by shouting that hogwash at me from afar? I implore"
        " thee to think again, peasant. As we converse I am contacting my secretive network of "
        "knights across the realm and thine footsteps are being traced right now, so thou best"
        " prepare thineself for the storm, pig-maggot! The storm that wipes out the pathetic"
        " little thing thou call your armour. Thou art a flipping dead man. I can be anywhere,"
        " anytime, and I can kill thou in over seven hundred ways, and that’s just with my bare"
        " lance. Not only am I extensively trained in mounted combat, but I hath access to the"
        " entire arsenal of the Kings Royal Army, and I shall use it to its full extent to wipe"
        " you're miserable derriere off the face of the realm, thou miniscule feaces. If only thou"
        " could have foreseen what unholy retribution your little “clever” challenge was about"
        " to bring down upon thee, maybe thou would have held thee flipping tongue. But thou"
        " couldn’t, thou didn’t, and now thee art paying the price, you godd¬amn fool. I shall "
        "s¬hit fury all over thou britches and thee will drown in it. Thou art flipping dead, child.",
        "are you kidding me you little piece of shit i’ll have you know i graduated top"
        " of my politics class and i’ve been involved in privilege checking with over"
        " 150 confirmed political demonstrations i’m trained in conflict resolution"
        " and i was the most oppressed person in my entire upper middle class high"
        " school you are nothing to me but another cultural appropriator i will wipe"
        " you the fuck out with precision the likes of which have never been seen o"
        "n this side"
        " of the 49th parallel mark my words you think you can get away with saying that shit"
        " to me over the internet think again fucker, as we speak i’m checking with my anarcho-communist"
        " analyst brigade for your location so you better be prepared to deal with some molotov"
        " cocktails and angry feminists flying through your window yOU’RE FUCKING DEAD CHERRY "
        "i can be anywhere at any time and i can kill you in over seven hundred ways and that’s"
        " just with me boring you to death while i talk about privilege not only am i extensively"
        " trained in hotline management but i have access to an entire arsenal of sociological "
        "articles to prove my point and i will use them to wipe your fucking face off the earth"
        " you little shit if only you had known what oppressed retribution your cultural"
        " appropriation would unleash then maybe you would have held your fucking tongue"
        " but you couldn’t you’re fucking dead kiddo",
        "What the fuck did you just fucking say about me, you little bitch?"
        " I’ll have you know I graduated top of my class at high school, and"
        " I’ve been involved in numerous /r/atheism frontpage posts,"
        " and I have over 300 confirmed facebook debate wins."
        " I am trained in theology and I’m the top debater on"
        " this entire website. You are nothing to me but just"
        " another target. I will wipe you the fuck out with"
        " precision the likes of which has never been seen"
        " before on this Earth, mark my fucking words. You"
        " think you can get away with saying that shit to"
        " me over the Internet? Think again, fucker. As"
        " we speak I am contacting my secret network of"
        " atheists across the Scandinavian peninsula and"
        " your IP is being traced right now so you better"
        " prepare for the storm, maggot. The storm that"
        " wipes out the pathetic little thing you call "
        "your life. You’re fucking dead, kid. I can be anywhere,"
        " anytime, and I can convince you that god doesn't exist"
        " in over seven hundred ways, and that’s just with my bare"
        " intellect. Not only am I extensively trained in debate,"
        " but I have access to the entire arsenal of my local library"
        " and I will use it to its full extent to wipe you're miserable"
        " ass off the face of this website, you little shit. If only you"
        " could have known what unholy retribution your little “clever” comment "
        "was about to bring down upon you, maybe you would have held your fucking tongue."
        " But you couldn’t, you didn’t, and now you’re paying the price, you goddamn idiot. "
        "I will shit fury all over you and you will drown in it. You’re fucking dead, skytard.",
        "What the fuck did you just fucking say about me you little conformist bitch? "
        "I'll have you know I graduated by the skin of my teeth in all my courses in community college "
        "and I've been making fucking pottery for my whole life and I listen to underground only music."
        " I am trained in whining and I'm the top douchebag in Starbucks. "
        "You are nothing to be but a fucking conformist."
        " I will wipe you the fuck out with shit so underground it's in China,"
        " mark my fucking words. You think you "
        "can get away with saying this shit to me over a fucking conformist site like Facebook? Think again, copy."
        " As we speak I'm contacting my manager at Barnes and Noble and he's got connections with"
        " every Apple store manager this"
        " side of the Mississippi, and your IP address is being traced so you better prepare for man slaps you"
        " little maggot. The man slaps that will knock you on your ass. "
        "You're fucking dead, conformist. I can get"
        " in my Prius and be anywhere in a matter of hours, anytime and I can"
        " berate you in 700 ways, and that's just "
        "in English. Not only am I able to speak languages no one else speaks,"
        " but I have access to your Twitter account"
        " and I will use it to its full extent to wipe out all your followers"
        " you little mainstream junkie. If only you could "
        'know what unholy retribution your little "clever" comment was about'
        " to bring down upon yo, maybe would have held your "
        "fucking tongue. But you couldn't, you didn't, and now you're paying the "
        "full price you goddamn mainstream loving bastard."
        " I will shit classic literature all over you, and you will drown in it. You're fucking dead, conformist.",
        "What's this you've said to me, my good friend? Ill have you know I graduated top of my class in conflict "
        "resolution, and Ive been involved in numerous friendly discussions, and I have over 300 confirmed friends."
        " I am trained in polite discussions and I'm the top mediator"
        " in the entire neighborhood. You are worth more"
        " to me than just another target. I hope we will come to have a friendship never before seen on this Earth."
        " Don't you think you might be hurting someone's feelings saying that over the internet? Think about it, "
        "my friend. As we speak I am contacting my good friends across the USA and your P.O. box is being traced"
        " right now so you better prepare for the greeting cards, friend. The greeting cards that help you with "
        "your hate. You should look forward to it, friend. "
        "I can be anywhere, "
        "anytime for you, and I can calm you"
        " in over seven hundred ways, and that's just with my chess "
        "set. Not only am I extensively trained in conflict"
        " resolution, but I have access to the entire group of my friends "
        "and I will use them to their full extent to"
        " start our new friendship. If only you could have known what kindness "
        "and love your little comment was about "
        "to bring you, maybe you would have reached out sooner. But you couldn't,"
        " you didn't, and now we get to start"
        " a new friendship, you unique person. I will give you gifts "
        "and you might have a hard time keeping up. You're"
        " finally living, friend.",
    ],
    "yccm": [
        "hi every1 im new!!!!!!! holds up spork my name is katy but u can call me t3h PeNgU1N oF d00m!!!!!!!!"
        " lol…as u can see im very random!!!! thats why i came here, 2 meet random ppl like me … im 13 years"
        " old (im mature 4 my age tho!!) i like 2 watch invader zim w/ my girlfreind (im bi if u dont like it"
        " deal w/it) its our favorite tv show!!! bcuz its SOOOO random!!!! shes random 2 of course but"
        " i want 2 meet more random ppl =) like they say the more the merrier!!!! lol…neways i hope 2 make alot of"
        " freinds here so give me lots of commentses!!!! DOOOOOMMMM!!!!!!!!!!!!!!!! <--- me bein random again ^"
        " hehe…toodles!!!!! ",
        "hi every1 im new!!!!! charges mah lazr my name is ted but u can call me Anonymous!!!!!!!! "
        "lol…as u can see im very random!!! thats why i came here, 2 meet random ppl like me … im 22"
        " years old (i still live w/ my mom tho!!) i like 2 look at mudkip threads with my boyfreind"
        " (im bi if u dont like it gtfo) its our favorite kindof thred!!!! bcuz their SOOOO random!!!!"
        " hes random 2 of course but i want 2 meet more random ppl =) like they say the more the merrier!!!!"
        " lol…neways i hope 2 make alot of friends here so give me "
        "lots of replieses! DESUDESUDESUDESUDESU!!!!!!!!!!!!!!!!"
        " <--- me bein random again  hehe…toodles!!!!! ",
        "hi every1 im new… holds up fedora. my name is bob but feel free 2 call me t3h fedora of D0oM!!!!!!!"
        " as u can see im very sophisticated and intelligent,…. that y i came to this atheist subreddit so i"
        " can meet other smart atheists -.- im 46 years old (i still act like im 10 lol) i like 2 watch jeopardy"
        ' w/ my grandma (yes ive seen her naked….) we enjoy yelling "suk it trebek" at the screen.. my grandma'
        " is smart 2 but she is a jew. so i came here 2 meet new people like me (smart atheists) like they say"
        " op is a faggot lol!!!! lol ok guyz anyways plz give me lots of upboats. I LIKE CEREAL!!!!!!!! oops"
        " sorry lol i have adhd lol ok toodles!!!!! ",
        "I am 13 – mature for my age, however! – and I enjoy watching Invader Zim with my girlfriend."
        " (I am bisexual. Please approach this subject maturely.) It is our favorite television show,"
        " as it adequately displays stochastic manners of behavior such as we possess.",
        "GREETINGS BATTLE BROTHERS I AM NEW. HOLDS UP BOLTER MY NAME IS SERGEANT ARGUS BUT"
        " YOU CAN CALL ME BATTLE BROTHER. AS YOU CAN SEE I AM VERY LOYAL TO THE EMPEROR."
        " THAT IS WHY I HAVE COME HERE, TO MEET OTHER BATTLE BROTHERS WHO ARE LOYAL TO THE"
        " EMPEROR LIKE MYSELF. I AM 127 YEARS OF AGE ( PRAISE THE EMPEROR) I LIKE TO PURGE"
        " HERETICS AND XENO SCUM WITH MY BATTLE BROTHERS ( I LOVE MY BATTLE BROTHERS, IF "
        "YOU DO NOT LIKE THAT THE DEAL WITH IT) IT IS OUR FAVORITE ACTIVITY BECAUSE THEY"
        " ARE NOT LOYAL TO THE EMPEROR. ALL MY BATTLE BROTHERS ARE LOYAL TO THE EMPEROR "
        "TOO OF COURSE, BUT I WANT TO MEET MORE LOYAL SERVANTS OF THE EMPEROR. LIKE THE "
        "EMPEROR ONCE SAID, THE MORE THE MERRIER. I HOPE TO BOND WITH A LARGE AMOUNT OF "
        "LOYAL SERVANTS OF THE EMPEROR SO JOIN ME IN PRAISE OF THE EMPEROR. FAREWELL.",
        "hi every1 im new!!!!!!! holds up rules my name is skeen but u can call me t3h "
        "k1ng 0f /r/ath3ism!!!!!!!! lol…as u can see im very skeptical!!!! thats why "
        "i created, 2 meet random skeptics like me ಠಠ… im 13 years old (im mature 4 my"
        " age tho!! in fact im an atheist!!!) i like 2 destoy christins w/ tuber (im bi"
        " if u dont like it deal w/it) its our favorite past time!!! bcuz its SOOOO rewarding!!!!"
        " hes skeptic 2 of course but i want 2 meet more random atheists =) like they say"
        " the more the merrier!!!! lol…neways i hope 2 make alot of subjcts here so give"
        " me lots of power!!!! LOL UR BANNED JIJ!!!!!!!!!!!!!!! <--- me bein moderator "
        "again again ^^ hehe…toodles!!!!! love and cheetos, ~t3h K1nG 0f /r/ath3ism~",
        "hi every1 im new!!!!!!! holds up Nexus with Android Police loaded my name is"
        " erica but u can call me t3h AnDrO1D oF d00m!!!!!!!! lol… as u can see im"
        " very open source!!!! thats why i came here, 2 meet hackers like me … im "
        "13 years old (im mature 4 my age tho!!) i like 2 watch APK teardowns w/ "
        "my girlfreind (im bi if u dont like it deal w/it) its our favorite google"
        " play show!!! bcuz its SOOOO open source!!!! shes open source 2 of course "
        "but i want 2 meet more open source ppl =) like they say the more MARKET"
        " SHARE the merrier!!!! lol…neways i hope 2 make alot of freinds here so"
        " give me lots of commentses!!!! ICECREAMSANWICCCHH!!!!!!!!!!!!!!!! <---"
        " me bein open source again ^ hehe…toodles!!!!! ",
        "Hello Fellow Oppressed Men…Holds Up Mens Rights Poster My Name Is John."
        " But Feel Free To Call Me Oppressed Man of Doom! As you can see,"
        " i am very oppressed by Child Custody Laws and Divorce Courts…."
        " That Is Why I Came Here To /r/MensRights, To Meet Other Mens Rights Advocates."
        " Im 14 Years Old(But I Pretend To Be 29 And Recently Divorced/Oppressed)."
        " I Like To Read AVoiceForMen W/ My Fedora On. We Enjoy Debating Women On FaceBook."
        " That Is Why I Came Here, To Meet People Like Me (Oppressed Mens) Like They Say Men"
        " Are Oppressed. Ok Guys Anyways Upvote This. Viva Le Revolution! <---------Just Me"
        " Proving Wmyn Wrong Again!",
        "Hello my fellow sirs and madams, "
        "I am a newcomer to this internet forum."
        " Gives you a complementary upvote as a token of friendship."
        " My name is niceguyplzdontfriendzone1, but you can call me a Gentleman and a Scholar."
        " As you can see I am very sophisticated and classy, that's why I came here, to meet "
        "other classy people like me. :) I'm 13 years old (I'm very mature for my age though!!)"
        " I like to watch Cosmos with Carl Sagan with my girlfriend (that's right I have a GIRLFRIEND"
        ", sorry ladies :P ), its our favorite TV show because it is so classy and intellegent! She's "
        "classy to of course but we want to meet more classy people! :) As they say, a Gentleman can never"
        " be to popular! Anyways, I hope to meet alot of sophisticated gents and ladies here so please don'"
        "t hesitate to respond (or PM me ladies ;) ). I bid you fellow my brethren as I go off to other great "
        "endeavors (me being classy again haha). Till our grand paths cross again, -A Gentleman and a Scholar",
    ],
    "arenot": [
        'Here\'s the thing. You said a "mountain lion is a lion." Is it in the same family? Yes.'
        " No one's arguing that. As someone who is a scientist who studies lions, I am telling you"
        ', specifically, in science, no one calls mountain lions "lions". If you want to be '
        "\"specific\" like you said, then you shouldn't either. They're not the same thing. If"
        " you're saying lion family\" you're referring to the taxonomic grouping of Felidae,"
        " which includes things from house cats to ocelots to tigers. So your reasoning for calling"
        ' a mountain lion a lion is because random people "call the big ones lions?" Let\'s get'
        " panthers and leopards in there, then, too. Also, calling someone a human or an ape? It's"
        " not one or the other, that's not how taxonomy works. They're both. A mountain lion is a"
        " mountain lion and a member of the lion family. But that's not what you said. You said a"
        " mountain lion is a lion, which is not true unless you're okay with calling all members "
        "of the lion family lions, which means you'd call house cats, tigers, and other cats lions,"
        " too. Which you said you don't. It's okay to just admit you're wrong, you know",
        'Here\'s the thing. You said a "chipmunk is a ground squirrel." Is it in the same family?'
        " Yes. No one's arguing that. As someone who is a scientist who studies squirrels, I am"
        " telling you, specifically, in science, no one calls chipmunks ground squirrels. If you"
        " want to be \"specific\" like you said, then you shouldn't either. They're not the same"
        " thing. If you're saying \"squirrel family\" you're referring to the taxonomic groupin"
        "g of Sciuridae, which includes things from prairie dogs to flying squirrels to marmots."
        ' So your reasoning for calling a chipmunk a ground squirrel is because random people "'
        "call the small ones ground squirrels?\" Let's get mountain beavers and dormice in there,"
        " then, too. Also, calling someone a human or an ape? It's not one or the other, that's not"
        " how taxonomy works. They're both. A chipmunk is a chipmunk and a member of the squirrel"
        " family. But that's not what you said. You said a chipmunk is a squirrel, which is not"
        " true unless you're okay with calling all members of the squirrel family chipmunks, which"
        " means you'd call prairie dogs, marmots, and other rodents squirrels, too. Which you said"
        " you don't. It's okay to just admit you're wrong, you know?",
        'Here\'s the thing. You said "Shrek is love." Are they in the same family?'
        " Yes. No one's arguing that. As someone who is a neuroscientist who studies"
        " emotions, I am telling you, specifically, in science, no one calls Shrek love."
        ' If you want to be "specific" like you said, then you shouldn\'t either. '
        "They're not the same thing. If you're talking about \"love\" you're referring "
        "to a wide range of emotions, which includes things from adoration to compassion "
        "to sentimentality. So your reasoning for calling Shrek love is because hundreds "
        "of random people have had intimate relations with him? Let's get my ex-wife in "
        "there, then, too. It's okay to just admit you're wrong, you know?",
        'Here\'s the thing. You said a "trilby is a fedora." Is it in the same family? Yes.'
        " No one's arguing that. As someone who is an atheist who studies euphoria, I am tell"
        'ing you, specifically, in atheism, no one calls trilbys fedoras. If you want to be "'
        "specific\" like you said, then you should too. They're not the same thing. If you're "
        'saying "fedora family" you\'re referring to the euphoric grouping of le reddit army,'
        " which includes things from neckbearded gentlesirs to highly intelligent intellectual"
        " like myself. So your reasoning for calling a trilby a fedora is because random people"
        ' "say that only neckbeards wear fedoras?" Let\'s get Mountain Dew and Doritos in there, then, too',
        'Here\'s the thing. You said a "a PC game is a sport." Is it in the same family?'
        " Yes. No one's arguing that. As someone who is a a mod of /r/pcmasterrace who "
        "studies PC games, I am telling you, specifically, in PC gaming, no one calls "
        'video games sports. If you want to be "specific" like you said, then you'
        " shouldn't either. They're not the same thing. If you're saying \"Video games\""
        " you're referring to the taxonomic grouping of MOBAS, which includes things from"
        " DOTA to LoL to SMITE. So your reasoning for calling a PC game a sport is becaus"
        'e random people "call the MOBAS Sports?" Let\'s get counter-strike and starcraf'
        "t in there, then, too. Also, calling someone a human or an ape? It's not one or"
        " the other, that's not how taxonomy works. They're both. A MOBA is a MOBA and a"
        " member of the Video game family. But that's not what you said. You said a PC "
        "game is a Sport, which is not true unless you're okay with calling all members"
        " of the video game family sports, which means you'd call Visual novels, RPG's,"
        " and other games sports, too. Which you said you don't. It's okay to just admit you're wrong, you know?",
        'Here\'s the thing. You said a "Jedi is a Sith." Is it in the same family? Yes'
        ". No one's arguing that. As someone who is a padawan who studies the Force, I "
        "am telling you, specifically, in this galaxy, no one calls Jedi Sith. If you"
        " want to be \"specific\" like you said, then you shouldn't either. They're "
        "not the same thing. If you're saying \"Sith family\" you're referring to the"
        " taxonomic grouping of Darksiders, which includes things from secret apprentices"
        " to masters to Dark Lords. So your reasoning for calling a Jedi a Sith is because"
        ' random people "call the black ones Sith?" Let\'s get Mace Windu and Lando Calrissian'
        " in there, then, too. Also, calling someone good or evil? It's not one or the"
        " other, that's not how the Force works. They're both. A Jedi is a Jedi and"
        " a member of the light side of the Force. But that's not what you said. You"
        " said a Jedi is a Sith, which is not true unless you're okay with calling"
        " all users of the Force Sith, which means you'd call Yoda, Luke, and other "
        "Force users Sith, too. Which you said you don't. It's okay to just admit you're"
        " wrong, you know?",
        'Here\'s the thing. You said a "espresso is coffee." Is it in the same family? '
        "Yes. No one's arguing that. As someone who is a Barista who studies Coffee,"
        ' I am telling you, specifically, in Coffee, no one calls espresso "coffee." '
        "If you want to be \"specific\" like you said, then you shouldn't either. They're"
        " not the same thing. If you're saying \"coffee family\" you're referring to the"
        " taxonomic grouping of potio aquam arabica, which includes things from French"
        " Press to Drip Coffee. So your reasoning for calling Espresso Coffee is because"
        ' random people call "Espresso" "Coffee"? Let\'s get Frappes and Instant Coffee '
        "in there, then, too. Also, calling someone a human or an ape? It's not one or "
        "the other, that's not how taxonomy works. They're both. Espresso is espresso "
        "and a member of the coffee family. But that\s not what you said. You said Espr"
        "esso is Coffee, which is not true unless you're okay with calling all members"
        " of the Coffee family Coffee, which means you'd call Frappés and Coffee-flav"
        "ored syrup \"Coffee\" too. Which you said you don't. It's okay to just admit yo"
        "u're wrong, you know?",
        'Here\'s the thing. You said a "queef is a fart." Is it in the same family? Ye'
        "s. No one's arguing that. As someone who is an Alabama redneck who studies fa"
        "rts, I am telling you, specifically, in Alabama, no one calls queefs farts. I"
        "f you want to be \"specific\" like you said, then you shouldn't either. They'"
        "re not the same thing. If you're saying \"fart family\" you're referring to t"
        "he gastronomic grouping of flatulence, which includes things from shit bubble"
        "s to tear-assers to Alabama mweep-mwoppers. So your reasoning for calling a q"
        'ueef a fart is because random people "call the ass ones farts?" Let\'s get d'
        "iarrhea and bloodfarts in there, then, too. Also, calling someone a Newfoundl"
        "ander or a gassy person? It's not one or the other, that's not how gastronomy"
        " works. They're both. A queef is a queef and a member of the fart family. Bu"
        "t that's not what you said. You said a queef is a fart, which is not true unl"
        "ess you're okay with calling all members of the fart family farts, which mean"
        "s you'd call piss, the runs, and other waste removal processes farts, too. Wh"
        "ich you said you don't. It's okay to just admit you're gassy, you know?",
        'Here\'s the thing. You said "SEALs are Special Forces." Can they fall under'
        " the same command? Yes. No one's arguing that, you little bitch. As someone"
        " who has over 300 confirmed kills, I am telling you, specifically, in the"
        ' military, no one calls SEALs SF. If you want to be "specific" like yo'
        "u said, then you shouldn't either. They're not the same thing. If you'r"
        'e saying "Special Operations" you\'re referring to the United States '
        "Special Operations Command, which includes things from Army Rangers to"
        " my secret network of spies across the USA. So your reasoning for calling"
        ' a SEAL SF is because random people "call the gorilla ones SF?" Let\'s get'
        " SOW and MRR in there, then, too. Also, calling someone DEVGRU or SEAL Team"
        " Six? It's not one or the other, that's not how Special Operations Command"
        " works. They're both. A SEAL is a SEAL and a member of USSOCOM. But that's"
        " not what you said. You said a SEAL is SF, which is not true unless you're"
        " okay with calling all operators of the USSOCOM family SF, which means you'd"
        " call Rangers, Pararescuemen, and other operators SF, too. Which you said you"
        " don't. It's okay to just admit you're fucking dead, kiddo.",
    ],
    "identify": [
        "I sexually Identify as an Attack Helicopter."
        " Ever since I was a boy I dreamed of soaring over the oilfields "
        "dropping hot sticky loads on disgusting foreigners."
        " People say to me that a person being a helicopter is Impossible"
        " and I'm fucking retarded but I don't care, I'm beautiful."
        " I'm having a plastic surgeon install rotary blades, 30 mm "
        "cannons and AMG-114 Hellfire missiles on my body. From now on I"
        ' want you guys to call me "Apache" and respect my right to kill from above and kill needlessly.'
        " If you can't accept me you're a heliphobe and need to check your vehicle privilege. "
        "Thank you for being so understanding.",
        "I sexually Identify as a ghost pirate."
        " Ever since I was a boy I dreamed of sailing the undead seas"
        " searching for the afterlife of dave jones' locker"
        " . People say to me that a person being a ectoplasmic-sea captain"
        " is Impossible and I'm fucking retarded but I"
        " don't care, I'm sp00ky. I'm having an ethereal cutlass created,"
        " a 17th century french sloop and a ghostly crew"
        " of shanty singers bought. From now on I want you guys to call me"
        ' "deadbeard" and respect my right to kill rival'
        " poltergeist and photonically phase my being into the next realm . If you can't accept me you're a"
        " phantom-buccaneerphobe and need to check your undead-aquatic privilege."
        " Thank you for being so understanding matey.",
        "I sexually Identify as a meme."
        " Ever since I was a boy I dreamed of being uploaded onto the imgur"
        " website and linked into the reddit threads."
        " People say to me that a person being a meme is Impossible and I'm fucking retarded but I don't care,"
        " I'm beautiful. I'm having a computer scientist put my brain "
        "into my computer like johnny depp in transendence, "
        "equipping me with the dankest of pictures from the internet."
        ' From now on I want you guys to call me "Sir Danks-a-lot"'
        " and respect my right to meme from above and meme needlessly."
        " If you can't accept me you're a memephobe and need to"
        " check your internet privilege. Thank you for being so understanding.",
        "I sexually identify as a Navy Seal. Ever since I was a child I"
        " dreamed of being the top sniper in the entire US armed "
        "forces. People say to me that having over 300 confirmed kills "
        "is impossible and I'm fucking retarded but I don't care,"
        " I'm beautiful. I'm having a secret network of spies trace your "
        "IP right now so you better prepare for the storm, maggot."
        " From now on, you're fucking dead, kiddo. If you can't accept me "
        "you need to check your gorilla privilege."
        " Thank you for being so understanding.",
        "I sexually Identify as a walrus. Ever since I was a boy I dreamed "
        "of sliding on cold ice with my manly genitalia. "
        "People say to me that a person being a walrus is Impossible and "
        "I'm fucking retarded but I don't care, I'm beautiful."
        " I already choped my arms and feet off and practice robbing around"
        " in my bathtub using my fingers as tusks."
        ' From now on I want you guys to call me "Arcticus" and respect '
        "my right to lay around on an iceberg and dive for free fishfood. "
        "If you can't accept me you're a zoophobe and need to check your"
        " Green Peace privilege. Thank you for being so understanding.",
        "I sexually identify as graph paper. Ever since I was a boy I dreamed"
        " of sorting over the grid drawing beautiful graphs on math homework. "
        "People say to me that a person being graph paper is impossible and I'm fucking retarded but I don't care, "
        "I'm beautiful."
        " I'm having a plastic surgeon tattoo rows, columns and 3 hole punches "
        "on my body. From now on I want you guys to call me "
        '"Grid" and respect my right to draw graphs and solve equations. '
        "If you can't accept me you're a papyrophobe and need to check your graphing privilege."
        " Thank you for being so understanding.",
        "I sexually identify as a single, Pringle,"
        " ready to mingle. Ever since I was a potato I"
        " dreamed of being thin sliced,"
        " covered in disgusting oil then heated in "
        "a medium oven until reaching climax at the micro second of golden-browness."
        " People bully me, and say things like"
        ' "what the fuck, you aren\'t a Pringle", but I know deep down they are just jealous of my inner beauty. '
        "I have already started hiding"
        " in cylinders all day, and now im improving my crunchiness by regularly burning my sides on the stove."
        " I want you guys to respect my natural ability to instantly satisfy low salt carb cravings, "
        "and if you don't you are oppressing me,"
        " and you should check your diabetes type. Thank you for being so understanding.",
        "I sexually Identify as an Neckbeard. Ever since I was a boy I dreamed of soaring "
        "over the Earth tipping m'fedora to beautiful m'ladies . People say to me that a person"
        " being a Neckbeard is Impossible and I'm fucking retarded but I don't care, I'm beautiful."
        " I'm having a plastic surgeon install anime in my veins , 30 mm fedoras and Meme"
        ' o\' missiles on my body. From now on I want you guys to call me "White Knight" and respect'
        " my right to meme from above and tip m'fedora when necessary . If you can't accept me you're "
        "an SJW and need to check your privilege. Arigato for being so understanding.",
    ],
    "roast": [
        "Astounding! You have managed to expend effort creating a non-random"
        " string of characters which usually convey meaning, yet your overall"
        " comment was ABSOLUTELY POINTLESS! It is as though all of the indust"
        "ries of mankind were operated in reverse, with great will and endeav"
        "or being used to convert items of usefulness into worthless bare mate"
        "rials! you are the antithesis of all that is grand and great about ma"
        "nkinds capacity for thought and self-determination. You sir, are the "
        "mirror image of a meaningful entity, lower than base matter, lower th"
        "an oblivion, because unlike the brutish deterministic plasma of the u"
        "nreasoning cosmos, you CHOSE to be without value or worth. Or in the "
        "parlance of thine own ilk: LOL N0 UR GAYYYYYYYYYYYYYY!!!11ONE!!!!!ELEVENTY!!!!11!﻿",
        "You've won nothing shithead. Wallow in the shit you've created. Becau"
        "se soon, all you've worked for will vanish and you'll be left with no"
        "thing. When you least expect it, the shit you talk, you'll choke on it.",
        "Downvoted. you're exactly what's wrong with circlejerk. Instead of pos"
        "ting satire, mocking reddit and being clever and original, you continu"
        "e to post lame phrases and beat to glue anything that was even remotel"
        "y funny, all under the guise that you want to show what's wrong with re"
        "ddit. You don't care about reddit. You belong to the system that this s"
        "ubreddit was made to mock. You seek karma. You seek to be a power-user,"
        " a well-known name in a sea of perpetual anonymity. The higher your kar"
        "ma-count, the more you get off on it. You are smug and self-satisfying."
        ' You are the problem. There should be a "delete" button below your po'
        "sts. Start clicking them after you post and you'll find that reddit star"
        "ts to improve.",
        "AT LEAST I DON'T SPEND MY TIME SUCKING DICKS IN THE BATHROOM AT OLIVE GA"
        "RDEN. YOU DIRTY LOWDOWN SLIMY FILTHY DISGUSTING GLUTTONOUS HOGLIKE MOTHER"
        " FUCKING COCK SUCKING SON OF AN INCESTUOUS PEDOPHILE SHEMALE RAPIST PROST"
        "ITUTE. GET YOUR MOM'S DICK OUT OF YOUR MOUTH. DO YOU KNOW WHAT I'M GONNA "
        "DO? I'M GONNA SHIT SO FAR UP YOUR ASS. STOP FOR A MOMENT AND REALLY GRASP"
        " THAT STATEMENT. I AM LITERALLY GOING TO SHIT UP YOUR ASS. I WILL TAKE MY"
        " PANTS OFF, RIP YOUR PANTS OFF, OUR SPHINCTERS WILL TOUCH, AND I WILL SHI"
        "T. YOU WILL TRY TO COUNTERSHIT. BUT MY SPHINCTER WILL OVERCOME. AND I WIL"
        "L PUSH A LOG OF SHIT FROM MY ASS UP INTO YOUR BODY. THIS IS WHAT SHALL O"
        "CCUR WHEN I FIND YOUR KEYBOARD FUCKING FACE. YOU KNOW WHAT ELSE? I WILL P"
        "ISS INTO A POT. I WILL ADD CORNSTARCH TO THE PISS AND BOIL IT UNTIL IT GET"
        "S REALLY THICK, LIKE SAUCE. I WILL POUR THE THICKENED PISS INTO A PLASTIC "
        "CONTAINER AND PUT IT IN THE FRIDGE UNTIL IT HARDENS INTO A FIRM JELLO. THEN"
        " I WILL THEN CUT IT INTO RECTANGLES. BATTER IT IN A MIX OF MILK, FLOUR, AND"
        " EGGS. AND DEEP FRY IT AT 375 UNTIL GOLDEN BROWN, FLIPPING ONCE SINCE THEY "
        "FLOAT. AND I WILL SERVE YOU MY DEEP FRIED PISS. THAT'S WHAT YOU GET FOR BEIN"
        "G SUCH A FAGGOT. COCKMUFFIN",
        "bitch u mad mf ugly b looking like the little ginger kid from little einst"
        "ein kill urself btch ill shoot u mf ass meet me irl fuck outta here wicho "
        "dorito ass shaped head btch albino gorilla lookin ass mf ill flame u dumb "
        "spotty white pizza shaped head lookin elongated ass nose marshmallow man c"
        "rusty ass mf self right here btch",
        "My Grandfather smoked his whole life. I was about 10 years old when my moth"
        "er said to him, 'If you ever want to see your grandchildren graduate, you h"
        "ave to stop immediately.'. Tears welled up in his eyes when he realized wha"
        "t exactly was at stake. He gave it up immediately. Three years later he die"
        "d of lung cancer. It was really sad and destroyed me. My mother said to me"
        "- 'Don't ever smoke. Please don't put your family through what your Grandf"
        'ather put us through." I agreed. At 28, I have never touched a cigarette. '
        "I must say, I feel a very slight sense of regret for never having done it,"
        " because your post gave me cancer anyway.",
        "I'm more educated than you, in every way shape and form."
        " Also more intelligent than you (exponentially so). I am"
        " better than you, in every facet of life, and I don't even "
        "know you, however, I just know, that I am. Also, we aren't "
        "bro's. If anything, you are someone I assign less value and "
        "worth than my own feces. Your life has no value, and you wil"
        "l make no contribution to this world, in your entire life, "
        "because of your low intelligence, and lack of skills. How d"
        "oes that feel, you fucking bottom denominator. go back to yo"
        "u vegan subreddit to fill your useless void of a life, prete"
        "nding it means anything. Am I a narcissist? I don't know, I "
        "am a fucking God. I will, do, and have succeeded in every fac"
        "et of life. I have done more, in this year alone, than you wil"
        "l have achieved before you leave this world... let that sink i"
        "n. You have no fucking clue who you are talking to. I am so vas"
        "tly superior, and intelligent, that I can infer all of this, wi"
        "th 100% accuracy. You are like a fucking ant, and I am a GOD"
        ". You do not even fly on my radar, let alone get acknowledgem"
        "ent, from the likes of me. I know you can sense my superiority"
        ", my power, my intelligence,and you are trying to pretend you "
        "don't feel it, its real. To conclude, go back to fucking yourse"
        "lf, you meaningless water-trash bottom feeding peasant.",
        "Wow. Okay. OKAY. OKAY. Yabba Dabba FUCK you and YABBA DABBA "
        "FUCK your shitty FUCKING memes. You are literally worth noth"
        "ing to me. If I saw your FUCKING UGLY ASS FACE on the street"
        ", I'd take a big loaded shotgun to your mouth, faggot. I have"
        " always wanted to murder you, your family, your friends, and y"
        "our pet goldfish since the day I was born. Brain Blast? How abou"
        "t I fucking blast your faggot ass brain with a shotgun. I want t"
        "o fucking candy crush your face through a mother fucking wall. Y"
        "ou are the reason why babies cry. Fuck your memes. Fuck you. Fuck"
        ". FUCK. FUCK. Try fucking saying that to be in REAL life where yo"
        "u aren't surrounded by a precious username and see what happens, w"
        "eakling. I have guns. Many guns. Guns that I could take to your hea"
        "d and blow it out right now. You hear me? Good.",
        "You fucking do that every damn time I try to talk to you about "
        "anything even if it's not important you just say K and to be h"
        "onest it makes me feel rejected and unheard like nothing would "
        "be better then that bullshit who the fuck just says k after you"
        " tell them something important I just don't understand how you t"
        "hink that's ok and I swear to god you're probably just gonna sa"
        "y k to this but when you do you'll know that you're slowly killin"
        "g me inside",
    ],
    "rns": [
        "If you are reading this,"
        " then you are wasting precious time reading the comments."
        " You will probably comment or like this, but you will waste"
        " more time. You are now thinking what I am on about, probably"
        " thinking that I am on something. However you are just wasting"
        " more time reading my comment. I have just wasted precious mom"
        "ents of your life that you could have spent sleeping or smoking"
        " weed. If you just realised, I have wasted more time explaining "
        "that I have wasted time. For this reason you might as well like"
        " this comment, as you might as well waste more time. Thank you"
        " for your wasted time.",
        "Imagine this. You are attracted to women, like you are now "
        "(emotionally and sexually), but they do not exist. They exis"
        "ted a long time ago, and no one knows what they looked like"
        " (They have a pretty good idea from the fossils, however),"
        " but they do not exist anymore. That means, not only do yo"
        "u know there will never be any possibility, of you having"
        " sex with one, but there;s not even a possibility of you "
        "ever seeing one in real life. Everyone else, however, exc"
        "ept for a very few, are not attracted to women, they are"
        " attracted to something else entirely. So, in other wor"
        "ds, you will never find any porn anywhere on the intern"
        "et, only non-sexual pictures of women. Everyone you hav"
        "e told about your attraction to women think it’s disgu"
        "sting. To relieve yourself, you get off on the non-sex"
        "ual pictures of women, knowing it will never get any be"
        "tter. That’s what life is like to me. I am a degree 6 Z"
        "oosexual, sexually and emotionally attracted to Tyrannos"
        "aurs and nothing else. Women don’t even do it for me. I a"
        "m cursed ",
        "forgive english, i am Russia, i come to study clothing"
        " and fashion at American university. i am here little "
        "time and i am very hard stress. i am gay also and this"
        " very difficult for me, i am very religion person. i n"
        "ever act to be gay with other men before. but after i a"
        "m in america 6 weeks i am my friend together he is gay "
        "also. He was show me American fashion and then we are kis"
        "s. We sex together. I never before now am tell my mothe"
        "r about gay because i am very shame. As i fock this Ame"
        "rican boy it is very good to me but also i am feel so g"
        "uilty. I feel extreme guilty as I begin orgasm. I feel "
        "so guilty that I pick up my telephone and call Mother i"
        "n Russia. I awaken her. It too late for stopping so I a"
        "m cumming sex. I am very upset and guilty and crying, s"
        'o I yell her, "I AM CUM FROM SEX" (in Russia). She say'
        ' what? I say "I AM CUM FROM SEX" and she say you boy,'
        ' do not marry American girl, and I say "NO I AM CUM FRO'
        'M SEX WITH MAN, I AM IN ASS, I CUM IN ASS" and my mothe'
        "r very angry me. She not get scared though.  I hang up phone"
        " and am very embarrass. My friend also he is very embarras"
        "s. I am guilt and feel very stupid. I wonder, why do I gay"
        " with man? But I continue because when it spurt it feel ve"
        "ry good in American ass.",
        "iPhone is the best console, and nobody could ever fuck"
        "ing speak against it. When I first got an iPhone, I wa"
        "s so excited that I wouldn't be trashy anymore. I got "
        "so many friends with the iPhone 5C's stunning colors a"
        "nd sexyness, and that isn't even half of it. It has over"
        " 30 GB worth of data. I was able to store, if I recall,"
        " 10,000 photos and it would only take up 4 gigabytes. It"
        " would play games that would seem laggy to a console and"
        " turn it into a lagless portable experience. I am a true"
        " fucking gamer, I play Angry Birds, Fruit Ninja, Flappy"
        " Bird, and Clash of Clans daily, I can message friends "
        "and stay up to date, I can talk to people with my face "
        "and always remember how my friends looked like, I can "
        "take endless photos with no worry about using data,"
        " and I could browse infinite pages of the internet,"
        " which a shitty console can't do. The PC, Wii, PS4,"
        " and Xbox 1 can't do any of this shit. Compete with"
        " that, consoletards. Also, nice trolling fucko, with "
        "you not including your fucking iPhone, get your "
        "facts strate Android fuckers.",
        "I r8 8/8: Gr8 b8, m8. I rel8, str8 appreci8, and congr"
        "atul8. I r8 this b8 an 8/8. Plz no h8, I'm str8 ir8."
        " Cr8 more, can't w8. We should convers8, I won't ber8,"
        " my number is 8888888, ask for N8. No calls l8 or out"
        " of st8. If on a d8, ask K8 to loc8. Even with a full "
        "pl8, I always have time to communic8 so don't hesit8."
        " dont forget to medit8 and particip8 and masturb8 to "
        "allevi8 your ability to tabul8 the f8. We should meet"
        " up m8 and convers8 on how we can cre8 more gr8 b8, "
        "I'm sure everyone would appreci8, no h8. I don't mean"
        " to defl8 your hopes, but its hard to dict8 where the"
        " b8 will rel8 and we may end up with out being apprec"
        "i8d, I'm sure you can rel8. We can cre8 b8 like alexa"
        "nder the gr8, stretch posts longer than the Nile's st"
        "r8s. We'll be the captains of b8, 4chan our first m8s "
        "the growth r8 will spread to reddit and like real est8"
        " and be a flow r8 of gr8 b8, like a blind d8 we'll col"
        "l8, meet me upst8 where we can convers8, or ice sk8 or"
        " lose w8 infl8 our hot air baloons and fly, tail g8. W"
        "e could land in Kuw8, eat a soup pl8 followed by a des"
        "sert pl8 the payment r8 won't be too ir8 and hopefull"
        "y our currency won't defl8. We'll head to the Israeli-"
        "St8, taker over like Herod the gr8 and b8 the jewish m"
        "asses, 8 million, m8. We could interrel8 communism, th"
        "ought it's past it's maturity d8, a department of st8,"
        " volunteer st8. reduce the infant mortality r8, all in "
        "the name of making gr8 b8 m8.",
        "I was only 9 years old I loved shrek so much, I had al"
        "l the merchandise and movies I pray to shrek every nigh"
        "t before bed thanking him for the life I've been given. "
        "Shrek is love I say, Shrek is life My dad overhears me a"
        "nd calls me a faggot I knew he was just jealous of my de"
        "votion for Shrek I called him a cunt He slaps me and sen"
        "ds me to go to sleep Im crying now, and my face hurts I "
        "lay in bed and its really cold A warmth is moving toward"
        "s me. I feel something touch me Its shrek I am so happy "
        'He whispers in to ear "this is my swamp He grabs me wit'
        "h his powerful ogre hands and puts me on my hands and kn"
        "ees I'm ready I spread my ass cheeks for Shrek He penet"
        "rates my butthole It hurts so much but I do it for Shrek "
        "I can feel my butt tearing as my eyes start to water I p"
        "ush against his force I want to please Shrek He roars a "
        "mighty roar as he fills my butt with his love My dad wal"
        'ks in Shrek looks him straight in the eye and says "Its'
        ' all ogre now" Shrek leaves through my window Shrek is '
        "love, Shrek is life",
    ],
}


@dataclass
class CopypastaLines:

    @staticmethod
    def gen_line(type: str):
        line_choice = advchoice(get[type])
        return line_choice
