#to update this make sure you unload and reload the fun cog.
get = [
    "Why did the man put his money in the freezer?\nHe wanted cold hard cash!",
    "What did the porcupine say to the cactus?\nIs that you mommy?",
    "What do you get when you cross a snowman with a vampire? \nfrostbite.",
    "How do crazy people go through the forest?\nThey take the psycho path.",
    "What do prisoners use to call each other?\nThey use cell phones",
    "What do you get from a pampered cow?\nSpoiled milk.",
    "Where do polar bears vote?\nThe North Poll.",
    "What did Geronimo say when he jumped out of the airplane?\nME!!!!!!!",
    "Where do snowmen keep their money?\nIn the snow banks.",
    "What's brown and sticky?\nA stick.",
    "Why do sea-gulls fly over the sea?\nBecause if they flew over the bay they would be bagels!",
    "What dog keeps the best time?\nA watch dog.",
    "Why did the tomato turn red?\nIt saw the salad dressing!",
    "What did the grape do when it got stepped on?\nIt let out a little wine!",
    "How do you make a tissue dance?\nPut a little boogey in it!",
    "Where do bees go to the bathroom?\nAt the BP station!",
    "What did the judge say when the skunk walked in the court room?\nOdor in the court.",
    "What did the water say to the boat?\nNothing, it just waved.",
    "What did the fish say when he swam into the wall?\nDam!",
    "Why don't skeletons fight each other?\nThey don't have the guts.",
    "What has four legs but can't walk?\nA Table!",
    "Why did the turtle cross the road?\nTo get to the shell station!",
    "What did the ground say to the earthquake?\nYou crack me up!",
    "What do you get when you cross a cow and a duck?\nMilk and quackers!",
    "Why did the elephant eat the candle?\nHe wanted a light snack!",
    'Why is the letter "G" scary?\nIt turns a host into a ghost',
    "What has  4 eyes but no face?\nMississippi!",
    "What did the spider do on the computer?\nMade a website!",
    "How do you find Will Smith in the snow?\nYou follow his fresh prints.",
    "My boss said to me, \"you're the worst train driver ever. How many have you derailed this year?\"\nI said, "
    "\"I'm not sure; it's hard to keep track.\"",
    "What is the king of all school supplies?\nThe Ruler.",
    "Manager: So do you think you'd be a good waiter?\nMe: Well, you could say I bring a lot to the table.",
    "An optometrist asks someone out on a date\n\"I have a couple of ideas... 1: Dinner. 2: Movies. "
    "1 or 2? 1.. 2..? 1..... or 2?\"",
    "What'd the cowboy say when he walked into the German car dealership?\n\"Audi...\"",
    "Can February march?\nNo, but April may.",
    "Breaking News: A movie theatre has just been robbed of over two thousand dollars\n"
    "The theives took a large soda and two bags of popcorn.",
    "I wanted to make a chemistry joke, but NaH.",
    "I used to really enjoy skiing, but that hobby went downhill so fast...",
    "I was inquiring about seating for two at a new restaurant and they asked if I had reservations...\n"
    "I said I had some, but that I was willing to give it a try.",
    "What did the clock do when it was hungry?\nIt went back four seconds.",
    "Two antennas got married. The ceremony wasn't that great, but the reception was outstanding.",
]
