from dataclasses import dataclass
from random import randint

from Functions.randomization import advchoice

varients = [
    "Windows 10",
    "Microsoft",
    "Ubuntu",
    "Debian",
    "Ratchet",
    "Steve",
    "Nascar",
    "Corn",
    "Jamming Lucy",
    "Blue",
    "Shaggy",
    "Scooby Snacks",
    "Cookies",
    "Barney",
    "Lamb",
    "Cheeseburger",
    "Ketchup",
    "Mustard",
    "Charles Darwin",
    "Swearing Banana",
    "Minion",
    "Peels",
    "Jimmy Neutron",
    "Cat&Dog",
    "Marven",
    "Squash",
    "Trace",
    "Tracey",
    "Fluffbutt",
    "Floofbutt",
    "Flurry Winter",
    "Flurry Summer",
    "Summer Fall",
    "Jack Rabbit",
    "Spinning Horse",
    "Purple Corn",
    "Purple Love",
    "Help me",
    "Found Love",
    "O' Really?",
    "Lubabababa",
    "Corn Forn",
    "Popping Pedals",
    str(randint(1, 30000)),
    "Bananas Foster",
    "Peach",
    "Cuddly Marshmallow",
    "Fantastic Troller",
    "Captain America",
    "Oo ee oo ah ah",
    "Oreo Pudding",
    "Golf Cart",
    "Wallah wallah",
    "Bang bang",
    "Mooncraft",
    "Simon Says",
    "McRonald's",
    "Floofy Cloud",
    "Arbee's",
    "NASCAR",
    "Paw Addiction",
    "Batman",
    "Ironman",
    "Paladerps",
    "Guardian",
    "Spinach",
    "Lollipop",
    "Bookworm",
    "Baked Beans",
    "Salted Caramel",
    "Doughnut Eater",
    "Pickles",
    "Nuggets",
    "Longest Yard",
    "Slippery Banana",
    "Coconut Cake",
    "Cheese Grater",
    "Cheese",
    "Peanuts",
    "Peanut Sauce",
    "ButterFingers",
    "Musketeer",
    "Steven Sergal",
    "Rush B",
    "I like pie",
    "Pie Eater",
    "Kitty",
    "AAAAA",
    "The Bees Knees",
    "qwerty",
    "Bleppy Floofball",
    "Undeniable Cutie",
    "Pie",
    "Apples",
    "A",
    "Perry Winkle",
    "Blue",
    "Steven",
    "Googly Bear",
    "Peppa Pig",
    "SpongeBob",
    "Scooby-Doo",
    "Shaggy",
    "Velma",
    "Fred",
    "Mystery Machine",
    "Daffy Duck",
    "Sammy",
    "K.I.T.T.",
    "Pizza",
    "Pepper",
    "Salt",
    "Chocolate Calculator",
    "Ribs",
    "Lettuce",
    "Tomato",
    "Unix",
    "Ubuntu",
    "Fedora",
    "RedHat",
    "Solus",
    "Zorin OS",
    "Windows Explorer",
    "Blueberry muffins",
    "Spinny Chair",
    "Mint",
    "Arch",
    "PrimeOS",
    "Windows 95",
    "Beans",
    "Furry Trash",
    "The Water Heater King",
    "Doge",
    "Ceiling Ket",
    "Windows Longhorn",
    "Kali Linux",
    "--- .-- ---",
    "AAAAA",
    "Billy Mays",
    "Mermaid Man",
    "Barnacle Boy",
    "Anemonemeony",
    "Mark's Pilers",
    "Full of Bees",
    "Light Yagami",
    "L",
    "Near",
    "Ryuk",
    "Explosive Poopy",
    "Syrup",
    "Honey",
    "Bames Nond",
    "Undeniably cute",
    "Incredible Fella",
    "Regular Raccoon",
    "Knighty Knight",
    "Detective Horse",
    "Fedora Ron",
    "Sour Pickle",
    "Pastel Durr",
    "Amber",
    "Angel",
    "April",
    "Art",
    "August",
    "Aurora",
    "Autumn",
    "Barb",
    "Bay",
    "Bill",
    "Bob",
    "Booth",
    "Brandy",
    "Brook",
    "Buck",
    "Candy",
    "Carol",
    "Cat",
    "Charity",
    "Chase",
    "Chip",
    "Clay",
    "Cliff",
    "Colt",
    "Cricket",
    "Crystal",
    "Daisy",
    "Dash",
    "Dawn",
    "Destiny",
    "Dixie",
    "Dolly",
    "Dory",
    "Dot",
    "Faith",
    "Fanny",
    "Faye",
    "Fern",
    "Flora",
    "Gale",
    "Ginger",
    "Grace",
    "Guy Fieri",
    "Hale",
    "Harmony",
    "Harry Potter",
    "Hazel",
    "Hazelnut",
    "Heath",
    "Heaven",
    "Holly",
    "Hope",
    "Iris",
    "Ivy",
    "Jade",
    "Jersey",
    "Jewel",
    "Jimmy Neutron",
    "John Cena",
    "Joy",
    "June",
    "Kitty",
    "Laurel",
    "Lily",
    "Marina",
    "Mark",
    "Mason",
    "May",
    "Mcdonald",
    "Melody",
    "Miles",
    "Milo",
    "Misty",
    "Nick",
    "Opal",
    "Pansy",
    "Patience",
    "Pearl",
    "Peg",
    "Penny",
    "Pepper",
    "Petunia",
    "Pierce",
    "Poppy",
    "Queen",
    "Red",
    "Reed",
    "Rich",
    "River",
    "Rock",
    "Rose",
    "Sandy",
    "Shepherd",
    "Skip",
    "Sky",
    "Sly",
    "Stone",
    "Summer",
    "Tab",
    "Tara",
    "Violet",
    "Winter",
    "Wren",
    ############################################################################
    # Valentines Day | Special thanks to Spirit of Shyness for help with these #
    ############################################################################
    #"Angel",
    #"Be Mine",
    #"Beautiful Petal",
    #"Call me",
    #"Cupcake",
    #"Cupid",
    #"Cutie 3.14",
    #"Cutie Pie",
    #"Floofy Bab",
    #"Got love?",
    #"Honeybun",
    #"Honeybunny",
    #"Love at First Sight",
    #"Lovey Dovey",
    #"Moonstruck",
    #"Purrfect",
    #"Soulmate",
    #"Sugarcube",
    #"Sugarpie",
    #"Sweetheart",
    #"Sweetie",
    #"Too Sweet",
    #######################
    # Saint Patrick's Day #
    #######################
    "Bagpipe",
    "Clover",
    "Dublin",
    "Emerald Isle",
    "Fortune",
    "Four-leaf Clover",
    "Gold",
    "Green",
    "Jig",
    "Lamb",
    "Leprechaun",
    "Luck of the Irish",
    "Magically Delicious",
    "Mischief",
    "Pot of Gold",
    "Rainbow",
    "Saint Patrick",
    "Shamrock Shake",
    "Shamrock",
    "Shepard's Pie",
    "Trifolium",
    #############
    # Halloween #
    #############
    # "Spoopy Ghost",
    # "Casper",
    # "Spooky Scary Skeleton",
    # "Trick or treat",
    # "Werewuff",
    # "Pumpkin",
    # "Jack-o-lantern",
    # "Totally not a ghost",
    # "Spoopy Booper",
    # "Zombie Floof",
    # "Gh0w0st",
    # "Haunted Howler",
    # "Pawranormal",
    # "The Great Pumpkin",
    # "Spooky Beans",
    # "Frankenstein",
    # "Ghouley",
    # "Bones",
    # "Jack-0w0-lantern",
    # "Rawr I'm scary!",
    # "Tingle",
    # "Dracula",
    # "Count Chocula",
    # "Booberry",
    # "Candy Corn",
    # "Candy Coworn",
    #############
    # Christmas #
    #############
    # "Dasher",
    # "Dancer",
    # "Prancer",
    # "Vixen",
    # "Comet",
    # "Cupid",
    # "Donner",
    # "Blitzen",
    # "Rudolph",
    # "Olive",
    # "Bough of Holly",
    # "Candy Cane",
    # "Decked Halls",
    # "Discount Rudolph",
    # "Eggnog",
    # "Feliz Navidad",
    # "Festivus Pole",
    # "Figgy Pudding",
    # "Frosty the Snowmew",
    # "Fruitcake",
    # "Gift",
    # "Grinch",
    # "Griswold",
    # "Holiday Ham",
    # "Holly",
    # "Jingly Bell"
    # "Krampus",
    # "Little Drummer Boy",
    # "Lump of Coal",
    # "Mince Pie",
    # "Noel",
    # "Nogged Egg",
    # "Old Saint Nick",
    # "Ornament",
    # "Partridge in a Pear Tree"
    # "Plum Pudding",
    # "Poinsettia",
    # "Roasted Chestnut",
    # "Santa Paws",
    # "Santa's Little Helper",
    # "Scrooge",
    # "Snowball",
    # "Stocking Stuffer",
    # "Sugarplum",
    # "Tinsel",
    # "Wrapping Paper",
    # "Wreath",
    # "Yule Log",
]


@dataclass
class Names:

    @staticmethod
    def get_name():
        names = set(varients)
        return advchoice(names)
