from dataclasses import dataclass

from Functions import randomization

"""{0} the running user, {1} the mentioned user"""

nsfw = {
    "hug": [
        "{0} hugs {1} while they are nude and covered in white substances.",
        "After {0} and {1} got done doing a doggy style in a very lewd way, "
        "{1} hugs {0} and kisses their lips while panting from the doggy style.",
        "{0} comes up behind {1} while {1} is drying off from the shower and hugs {1}.",
        "{0} grinds up against {1}'s crotch in a steamy hug.",
        "{0} rips {1}'s clothes off and holds them close in a tight hug.",
        "{1} gets hugged by a cum-covered {0} after stepping out of the shower. "
        "Looks like they're going to need anther one.",
        "{1} shudders and moans for more as {0} sensually bites them while hugging.",
        "{1} is eagerly glomped by {0}, who's wearing their birthday suit complete "
        "with whipped cream and sprinkles on the naughty bits.",
        "{0} grinds their body against {1} and starts opening their hands to hug them.",
        "{0} smiles in a lewd manner as they come in to hug {1}.",
        "After a playful intimate session {0} hugs {1} in the shower.",
        "{0} casually walks up to {1} from behind and rubs them sexually while hugging.",
        "While {0} has been in heat for a long time, they come over and lewdly hug {1}",
        "After a rough kinky session, {0} and {1} sit together in bed and hug each other.",
    ],
    "tease": [
        "{0} strips down to tease {1} in a sexual manner.",
        "{0} silently watches {1} stare at them while they shower.",
        "{0} begins to tease {1} by masturbating!",
        "{0} begins to slide their underwear down in front of {1} in attempt to tease them.",
        "{0} gently sits down besides {1} while they begin sliding a paw up their shirt.",
        "{1} is sitting on the edge of the pool when ",
        "{0} begins going into a pool naked making {1} have sexual thoughts.",
    ],
    "seduce": [
        "{0} uses their body to seduce {1}.",
        "{0} giggles as their body makes {1} inclined to have sex with them.",
        "{0} begins flirting with {1} in attempt to seduce them into an sexual experience",
        "While {0} steps out of the shower and begins drying off, "
        "he/her walks outside of the bathroom and begins seducing"
        " {1} who was waiting patiently to take a shower next",
        "{0} stares at {1} and waves their paw for {1} to come over to him/her."
        " While {1} begins to walk over, {0} poses in a seductive manner.",
    ],
    "cuddle": [
        "While {1} is laying on their bed naked, {0} comes over and cuddles against their nude warm body.",
        "While {1} is taking a bath {0} joins them and cuddles with them.",
        "{0} crawls in {1}'s bed and snuggles them very sexually",
        "{0} fingers {1} as they cuddle the night away",
        "{0} and {1} make a mess of each other in cummy cuddles",
        "{0} cuddles {1} and licks cum from their snoot",
        "{0} surprise cuddlefucks {1}, who moans in pleasure and passionately nuzzles into them.",
        "After a long intense session of spooning, {0} cuddles really passionately with {0}.",
        "{0} huffs very quietly after a very long day and passionately cuddles {1}.",
        "{0} is laying in bed and cuddles {1} in a lewd manner and {} starts moaning.",
        "'Ready for the ultimate cuddle?', {0} says to {1} as they pounce in their"
        " birthday suit towards {1} and cuddles them",
        "{0} notices that {1} seemed lonely in their bath, so {0} comes in and cuddles them.",
        "{0} and {1} were watching a romantic movie and {0} cuddles {1} while touching their desirable parts.",
        "'Give me your cummies!', Says {1} towards {0}, but instead {0} cuddles them instead.",
        "After listening to their neighbors having sex (they were very loud), "
        "{0} approaches {1} naked, and begins rubbing their body against {1} and cuddles with a lewd smile.",
    ],
    "kiss": [
        "{0} kisses {1} while {0} continues to bang them violently as they moan loudly.",
        "{1} is currently laying down. {0} lays on top of "
        "them naked and kisses them deeply, leaving {1} horny and begging for more",
        "{0} and {1} share a passionate cummy kiss, savoring each other's juices before slowly swallowing.",
        "While {0} is french kissing {1}, {0} begins rubbing {1} in a sexual manner.",
        "{0} is laying in bed with {1} and they are kissing while having sex.",
        "While {0} is covered in {1}'s cum, they passionately come in and tounge kisses {1}, making {1}'s "
        "face all messy with their cum.",
        "'Harder', {1} says while in a intense pounding from {0} and {1} tounge kisses as {1} cums really hard.",
        "{0} blushes extremely dark while {1} rubs {0}'s desirable parts and {0} kisses {1} for being "
        "such a good floof.",
        "While {1} is tied down and fucked silly, {0} kisses their desirable parts.",
    ],
    "lick": [
        "{1} has been licked deeply by {0}",
        "{0} licks {1} from head to toe, making them nice and wet inside and out",
        "{0} licked {1} in a very special way that they will never forget.",
        "{0} licked {1} while they both moaned in pleasure",
        "{0} lewdly licks {1}, who can't help but join in on the fun",
        "{0} makes {1} lick whipped cream and sprinkles off of their naughty bits.",
        "{0} starts licking {1}'s private area, making them let out a loud moan.",
        "{1} asks {0} to lick their mess off of {1}'s body",
    ],
    "bang": [
        "{0} banged {1} until they moaned very loudly",
        "{0} banged {1} until they came",
        "{0} pushed {1} onto the bed and started banging them",
        "'Oh baby, Give me more', {1} says as {0} continues to bang them.",
        "{0} bangs {1} doggy style.",
        "'Harder~!', {1} says while being banged by {0}",
        "{1} floods with cum while being banged by {0}",
        "{1} begs for more while drenched in cum from {0}",
    ],
    "suck": [
        "{0} sucks {1} with hungry eyes.",
        "{0} sucks {1} while blushing really hard and wet.",
        "{0} kneels towards {1} and begins sucking their dick/pussy.",
        "{0} playfully sucks {1} really hard.",
        "{0} sucks {1} while rubbing themselves."
    ],
    "whip": [
        "{0} whipped {1} in a sexy way.",
        "{0} tied up {1} to a chair, and whipped {1} legs.",
        "{0} ties up {1} in a lewdy way and whips very nicely.",
        "{0} bends {1} over and whips their ass.",
        "{0} pushes {1} against a wall and whips them.",
        "{0} grabs {1} and whips them on their desirable parts!",
        "{0} grabs {1} and whips them all over!",
        "{0} pushes {1} onto a table and whips them all over!",
        "{1} bends down to pick up something and {0} gives them a big whack on their butt.",
        "{1} wiggles their ass while {0} comes over and gives them a nice tap on their bootie.",
        "{0} comes over to {1} and gives them a big ol smack on their bootie.",
        "{1} walks near {0}, and {0} taps them on {1}'s ass.",
        "{0} giggles and smacks {1}'s ass.",
    ],
    "bulge": [
        "{0} examines {1}'s bulge",
        "{0} stares at {1}'s bulge",
        "{0} inspects {1}'s package",
        "{0} just can't seem to take their eyes off of {1}'s bulge",
        "{0} notices {1}'s bulge and impulsively shouts \"OwO what's this?\"",
        "{0} firmly rubs their paws on {1}'s bulge",
        "{0} licks {1}'s bulge lovingly",
        "{0} nuzzles and licks {1}'s bulge affectionately",
        "{0} playfully nibbles {1}'s bulge",
        "{0} couldn't contain themselves after seeing {1}'s bulge and begins to rub and fondle it"
    ],
    "wags": [
        "{0} wags their tail at {1} with a lewd smile.",
        "{0} wags their tail at {1} while looking at them with kinky eyes.",
        "{0} wiggles as their tag sways back and forth at {1}.",
        "{0} wags their tail while {1} covers them in their juice.",
        "{0} wags their tail while {1} is banging them.",
    ],
    "finger": [
        "{0} begins to finger {1} nice and deep making them blush.",
        "{0} fingered {1} until they came.",
        "{1} moans in pleasure as they get fingered by {0}.",
        "{1} squeaks loudly as {0} fingers deep and hard.",
    ],
    "bound": [
        "{0} bound {1} until they begged to cum!",
        "{0} bound {1} to a chair and fingered them.",
        "{0} bound {1} and made them beg for pleasure.",
        "{0} intricately ties {1} up in a beautiful arrangement of asanawa",
        "{1} is cuffed to a bed by {0}, who's wearing a sexy tight-fitting police uniform",
    ],
    "pickup": [
        "ay {} do you like tapes and cd's? cuz i'm about"
        " to tape this dick to your forehead so you can see deez nuts \U0001f643",
        "ay {} why don't you treat me like a pirate and give me that booty. \U0001f643",
        "ay {}, are you a gorilla exhibit? cuz I wanna drop a kid in you \U0001f643",
        "go ahead and run {}, I like my meal to squirm.",
        "ay {}, call me leaves cuz you should be blowing me right now \U0001f643",
        "ay {}, I like every bone in your body, especially mine \U0001f643",
        "ay {}, let’s play Barbie. I’ll be Ken and you can be the box I come in. \U0001f643",
        "Hey {} wanna play carnival? You sit on my face and I'll guess how much you weigh. \U0001f643",
        "ay {}, lets play “Titanic”. When I say “Iceberg!” you go down. \U0001f643",
        "ay {}, I’m no weatherman, but you can expect more than a few inches tonight. \U0001f643",
        "ay {}, Charizards is red, Squirtles are blue, if you were a Pokemon I would choose you!",
        "ay {}, If you were a squirrel, would you help me bust a nut?",
        "ay {}, I heard you are looking for a stud. I’ve got the STD, all I need is U.",
        "ay {}, Do you know your ABC’s? Cause I wanna give you the 4th letter of the alphabet.",
        "ay {}, Is there a cell phone in your back pocket? Cause that ass is calling me!",
        "ay {}, Are those fuck me eyes, or fuck you eyes?",
        "ay {}, your legs are like an Oreo Cookie - I wanna split them and eat all the good stuff in the middle.",
        "ay {}, Are those lumberjack pants you're wearing? They are giving me a wood.",
        "ay {}, If your right leg was Christmas and your left leg was"
        "Easter, would you let me come for dinner between the holidays?",
        "ay {}, Wanna go on an ate with me? I'll give you the D later.",
        "ay {}, Let's go back to my room and do some math: Add a bed,"
        "subtract our clothes, divide your legs, and multiply.",
        "ay {}, I wanna paint you green and spank you like a disobedient avocado.",
        "ay {}, If it's true that we are what we eat, then I could be you by tomorrow morning.",
        "ay {}, If you were an elevator, what button would I have to push to get you to go down?",
        "ay {}, What if I start this relationship with you as a frien."
        "Will you allow me to give you the 'D' later?",
        "ay {}, I'm like Domino's Pizza. If I don't cum in 30 minutes, the next one is free.",
        "ay {}, Let's have a party and invite your pants to come on down.",
        "ay {}, Are you an architect, cause I want you on staff for my next erection.",
        "ay {}, Do you like Imagine Dragons? Well Imagine Dragon my balls across your face.",
        "ay {}, Is your name Autumn, cause I'd fuck you so hard all your leaves will fall off.",
        "ay {}, My penis is like a dictionary want me to blow your mind?",
        "ay {}, my hole is open for business, why won't you come an live in my hole?",
        "ay {} If I said I worked for FedEx, would you let me handle your package?",
        "Hello, gorgeous. I’m like a tropical island. I am hot, wet and ready for visitors.",
        "{} You must be Medusa because you make me rock hard.",
        "{} Are you a mirror? Cause I can see myself inside you.",
        "{} Baby I’m like a firefighter I find them hot and leave them wet.",
        "{}, I’ll treat you like my homework: Slam you on the table and do you all night long!",
        "{}, Hey baby, are you a pet? Because I want to own you.",
        "{}, Hey are you sitting on a F5 key? Cause that ass sure is refreshing.",
        "{}, if i where a enzyme i would would be a helicase, so i could unzip those genes of yours",
        "{}, Are you a mideastern leader, because you're causing a political uprising in my pants",
        "{}, Hey baby, you must be a light switch, coz every time I see you, you turn me on!",
        "{}, Are you a pie? Because you taste delicious.",
        "{}, My magical watch says you aren’t wearing any panties. Oh, you are? It must be an hour fast!",
    ],
    "pounces": [
        "{0} pounces on {1} while they were doing the masturbation thing.",
        "{1} blushes as {0} pounces on them while naked.",
        "{1} drools watching {0}'s bits jiggle from pouncing on their chest."
    ],
    "group": [
        "{0} pushes {1} and {2} together while they finger both of them.",
        "{1} and {2} rubs {0} in a sexy manner.",
    ],
    "hold": [
        "{0} slowly holds {1} with deep love and compassion",
        "{0} holds {1} hand(s) as they make passionate love with each other(s)",
        "As {0} licks {1}'s desirable parts, they hold their face calmly while they moan softly.",
        "As {0} sucks on {1} dick/boobs, they grope their ass/boobs."
    ],
    "clean": [
        "{} cleans up {}'s parts from a long session of having sexual intercourse.",
        "{} wipes {}'s parts as they begin to have sexual intercourse with them.",
        "{} giggles while they clean off the cum off {}.",
    ],
    "spank": [
        "{0} spanks {1} for disobeying their master.",
        "{1} begs for more as {0} relentlessly spanks them!",
        "{0} unleashes the fury of a thousand paddle strikes upon {1}'s backside! **C-c-c-combo breaker!**",
    ],
    "ride": [
        "{0} climbs on to {1} and rides their fat cock!",
        "{0} pulls {1} into their tight hole",
        "{0} pushes back and takes {1} cock into you their tight hole.",
        "{1} moans as {0} rubs their intimate areas together",
    ],
    "booty": [
        "{} wiggles their booty at {}",
        "{} shows off their rear end to {}",
        "{} lets {} use their butt as a pillow.",
        "{} fucks {}'s ass, making it jiggle like Jello.",
        "{} uses {}'s face as a chair to sit on for their big butt."

    ],
    "creampie": [
        "{0} pushes their member deep inside {1} and unleashes a hefty load inside them.",
        "{0} moans as they unleash a massive milky load in {1}.",
        "After hours of fucking {1} desirable parts, {0} begins to unleash a creamy milky load inside them.",
        '{1} moans loudly and says to {0}, "Cum in me.....". By {1}\'s request, {0} cums inside them.',
        "{1} pants heavily while {0} makes their parts covered in a white substance."
    ],
    "solo": [
        "{0} lays down and allows {1} to watch them masturbate.",
        "{0} starts to undress in front of {1} and begins to masturbate.",
        "{1} accidentally walks in on {0} while they were doing their naughty business",
        '{0} smiles and moans in pleasure loud enough to make {1} to make sure they were alright and was'
        ' surprised at what they found.',
        "{0} couldn't resist their heat and stripped in front of {1} and began to masturbate"
    ],
    'presentation': [
        '{0} presents their parts to {1}',
        'While {0} is in heat, they present themselves to get pleasured by {1}',
        '{0} lays down on the couch, revealing their parts to {1} purposely',
        '{0} plays with themselves while presenting their goods to {1}',
        '{0} has a blast presenting themselves to {1}'

    ]
}

sfw = {
    "boop": [
        "{1} has been booped by {0} while giggling",
        "{1} was booped by {0}",
        "{0} runs over to {1} and boops them",
        "{0} unloads a barrage of fully automatic assault boops upon {1}",
        "{1} blushes and hides their face as they are suddenly booped by {0} while looking at something on {1}'s computer screen.",
        "{0} boops {1} and smiles derpily, then boops them again and again and again until the end of time.",
    ],
    "nuzzles": [
        "{0} and {1} relax together, nuzzling each other in a loving embrace.",
        "{0} nuzzles {1} affectionately to keep warm on a cold night. How adorable~!",
        "{0} sits down with {1}, nuzzling them in their lap.",
        "{0} lays down with {1}, nuzzling after a hard day.",
        "{0} nuzzles {1} in bed before they fell asleep.",
        "{0} nuzzles {1} as they watch a romantic movie.",
        "{0} nuzzles {1} with passionate love as they watch the sunset.",
    ],
    "kiss": [
        "{0} kisses {1} while being aroused.",
        "{0} kisses {1} in a romantic way.",
        "{0} kisses {1} in a unforgettable way.",
        "{0} kisses {1} in a magical way.",
        "{0} comes close to {1} giving them the kiss of their dreams.",
        "{0} smiles warmly as {1} approaches them while {0} puckers up and kisses {1}.",
        "{0} hugs and kisses {1} while they are feeling down.",
        "{0} kisses {1} in an attempt to show their love to them.",
        "{0} cuddles {1} and they kiss so gently.",
        "{0} covers {1}'s cheek in lovey smooches.",
        "{0} stood up in front of {1} and gave a bold kiss",
        "{0} surprised {1} when they kissed them unexpectedly",
        "{0} waltzed up to {1} while they were blushing and kissed them",
        "{0} blushed so hard from the thought and just kissed {1}",
        "without thinking {0} kissed {1} and blushed",
        "{0} thought about {1} and decided to go up to them and kiss them",
        "{0} was so lovingly that they kissed {1}",
        "{0} felt so happy that they kissed {1}",
        "{1} blushed so hard when {0} kissed them",
        "{1} didn't expect it but {0} kissed them",
        "{0} was nervous at first but kissed {1}",
        "{0} had feelings for {1} and kissed them",
        "{0} let themself kiss {1} all so lovingly",
        "{0} decided to give a kiss to {1}",
        "{0} went ahead of themself and kissed {1}",
        "{0} blushed nervously after kissing {1}",
        "both {0} and {1} blushed when they kissed",
        "both {0} and {1} were nervous but they kissed",
        "{1} felt beloved by {0} when they kissed",
        "{0} was feeling confident and kissed {1}",
        "{0} hesitated at first but then kissed {1}",
        "{1} was hesitant but then {0} kissed them first before they could",
        "{0} was nervous when they kissed {1}",
        "{1} was surprised when {0} kissed them",
        "{0} unexpectedly kissed {1} without warning",
        "{0} hesitantly walked over to {1} and kissed, blushing after",
        "{0} kissed {1} and they blushed nervously while doing it",
        "{0} felt so nervous at first but finally kissed {1}",
        "{1} was talking away when unexpectedly they get kissed by {0}",
        "{0} walked up slowly to {1} so confidently that they kissed",
        "{1} felt loved when they were kissed by {0}",
        "{0} and {1} were sitting together on a bench in the park when they kissed",
        "{0} and {1} were eating when they kissed",
        "{0} went and surprised {1} when they kissed them",
        "{0} smiled as they walked up to {1} and kissed them",
        "{0} smiled as they kissed {1}",
        "{0} felt so happy when they kissed {1}",
        "{0} felt embarrassed after they kissed {1}",
        "{0} and {1} felt embarrassed after they kissed",
        "{0} and {1} both smiled to each other after they kissed",
        "{0} smiled nervously after they had kissed {1}",
        "{1} smiling when unexpectedly they were kissed by {0}",
        "{0} got up from where they sat and stood in front of {1} and kissed",
        "{0} moved over to {1} and kissed",
        "{0} and {1} were so embarrassed after they had kissed",
        "{1} was sitting alone when {0} came by and sat down next to them and kissed them",
        "{0} nervously walked with {1} when they kissed",
        "{1} was walking alone when {0} came across them and kissed them",
        "as the sun set {0} went and kissed {1}",
    ],
    "hug": [
        "{0} opens their arms for {1} so they could get a lovable hug from {0}",
        "{0} hugs {1} in a lovable way",
        "{0} hugs {1} with a very warm smile",
        "{0} hugs {1} in an attempt to cheer them up",
        "{0} chases {1} down to give {1} a loving hug",
        "{0} sneaks up behind {1} and gives them a surprise hug!",
        "{0} lunges at {1}, wrapping their arms around them lovingly!",
        "{1} wasn't suspecting anything at first, but then suddenly {0} appears and hugs them!",
        "{0} blushes a little bit, carefully approaching {1}, and gives them a tender hug.",
        "{0} suddenly yells out loud; 'Tactical hug incoming!'. "
        "They lift {1} from the ground and hugs them tightly.",
        "{0} distracts {1} by pointing at the sky. Then, when {1} is turned around, {0} hugs them from behind!",
        "{0} whistles inconspicuously as he walks past {1}, but "
        "they turn around and give {1} an unexpected hug!",
        "{0} and {1} run towards each other, arms open, "
        "not unlike the classic grassy-field-reunion scene. They meet in the middle with a strong embrace.",
        "{0} scoots closer over to {1} on a park bench, "
        "then wraps their arms around the unsuspecting hug victim."
        "{0} confidently steps forward, giving {1} a tight hug.",
        "{0} gives {1} a big ol' hug.",
        "{1} is suddenly hugged by {0}!",
        "Unexpectedly {0} went up to {1} and hugged them tightly",
        "{0} sneakily walked up behind {1} and gave them a fluffy hug",
        "As shy {0} may be, they brought up enough courage to hug {1} without hesitation",
        "As {1} talked, {0} went up to them and hugged them",
        "{1} seemed all alone so {0} gave then a hug to make them see that they are not alone",
        "{1} seemed upset so {0} goes up to them and gives them a comforting hug to cheer them up",
        "{0} got up from where they were and gave {1} a friendly hug",
        "{1} asked for a hug from {0} and got what they wanted",
        "After a long trip back home, {0} hugged {1}",
        "{0} was excited to see {1} and hugged them tightly with a smile on both of their faces",
        "{0} ran up close to {1} and hugged them tightly",
        "{0} went up to {1} hesitantly and managed to give then a poofy hug",
        "{0} stamped up close to {1} and hugged them tightly with a smile",
        "{0} turned towards you and gave {1} a warm hug",
        "{0} strolled past {1} and came running back with a fluffy hug",
        "As {1} walked, {0} ran after and hugged them",
        "{0} saw {1} ran up to them and gave a friendly hug",
        "{0} ran up behind {1} and tackle hugged them",
        "{0} felt so happy that they hugged {1}",
        "{1} felt so alone until {0} came up and sat beside them and hugged them",
        "{0} cheerfully waltz up to {1} and gave then a tender hug",
        "{0} ran and hug tackled {1} to the ground",
        "{0} ran up to a friend, {1}, and gave them a firm hug",
        "{0} jumped up at {1} and attack hugged them",
        "{0} seen {1} and got up from where they sat and walked over for a nice hug",
        "{0} went up and hugged {1}, a little shy but managed to do it",
        "{0} and {1} gave each other a warm hug",
        "{0} finally decided to hug {1} with a nice warm hug",
        "{0} felt shy at first but mustered up all they could and walked up to {1} and hugged them",
        "{1} was sitting alone at a bench when {0} sat down next to them and hugged them tightly",
        "{1} was waiting outside when {0} came up and hugged them",
        "{0} and {1} were sitting on the couch when they hugged each other",
        "{1} wanted a hug when {0} volunteered and gave them a good hug",
        "{0} felt like giving a hug and {1} happily volunteered for the hug",
        "{1} walked into their house and was welcomed by {0} who gave them a hug",
        "{1} was working when {0} came up and hugged you",
        "{1} walked out of a store when they unexpectedly received a hug from {0}",
        "{1} was walking home to their house when {0} came up behind them and gave them a tight hug",
        "{1} was eating when {0} hugged them from behind",
        "{0} walked up to a random person named {1} and hugged them",
        "{0} and {1} were walking together in a forest when out of nowhere they hug each other",
        "{0} and {1} were watching a good movie when they hug each other",
        "{1} arrived and got hugged by {0}",
        "{0} walked from their house and came to hug {1}",
        "{0} moved over to {1} and gave then hugs",
        "{1} stamped by {0} and they go to hug to make them feel better",
        "{1} was crying so {0} came by and hugged them a warm hug",
        "{1} was sitting at a bench in the park when {0} came by and gave a friendly hug",
        "{0} blushing from the thought and goes to hug {1} firmly and tightly",
        "{1} felt depressed until {0} came up and gave them a friendly hug",
    ],
    "lick": [
        "{0} licked {1} to the point where they murred and wiggled",
        "{0} licks {1} and makes them purr",
        "{0} licks {1} affectionately and makes them coo softly and happily",
        "{0} licked {1} in the name of love. Murr!",
        "{0} was feeling a little playful and decided to lick {1}",
        "{0} slides over to {1} and licks them",
        "{0} nibbles and licks {1} playfully",
        "{0} slides over to {1} and gives them lots of licks and cuddles",
    ],
    "cuddle": [
        "{0} cuddles {1} to comfort them in their time of need",
        "{1} is grabbed by {0} for a cuddle",
        "{0} whistles {1}, come cuddle with me. {1} comes and cuddles {0}",
    ],
    "pounces": [
        "{0} pounces on {1} in a happy playful mood",
        "{0} looks at {1} and pounce on them with a very smirky smile.",
        '"I\'m going to pounce you!" and {0} pounces {1}',
        "{0} pounces {1} with a high quick response.",
        "{0} pounces {1} on their bed.",
        "{0} pounces on {1} giving them snuggles till they couldn't breath!",
        '{0} pounces on {1} ,"Tag your it!"',
        "{0} pounces on {1} tickling them till they squealed!",
        "{0} swoops down on {1} giving them a big surprise!",
        "Unexpectedly, {0} pounces on {1} making {0} fall flat into the snow!",
        "{0} locks onto {1} and does a well-aimed pounce onto the floor!",
        "{0} knocks over {1} with a powerful pounce,"
        " but to {0}'s surprise, {1} retaliates with a pounce of their own!",
    ],
    "hold": [
        "{0} holds {1} with a deep passionate smile.",
        '"I\'m never letting you go", {0} says to {1} while holding them',
    ],
    "wags": [
        "{0} murrs/purrs at {1} while they wag their tail happily.",
        "{0} smiles at {1} while they playfully wag their tail.",
        "{0} flicks their tail at {1} while {1} nearly sneezes"
        " from their nose being tickled.",
        "{0} walks up to {1} and {0} wags their tail in excitement.",
        "{0} cuddles with {1} and {0} wags their tail.",
    ],
    "pickup": [
        "ay {}, Charizards is red, Squirtles are blue, if you were a Pokemon I would choose you!",
        "ay {}, If you were a chicken, you'd be impeccable.",
        "ay {}, Do you sleep on your stomach? If not, can I?",
        "ay {} You are like the best coffee: tall, dark and strong ",
        "{} Are you a camera? Because every time I look at you, I smile",
        "{}, Do you have a name or can I call you mine?",
        "{}, Are you the cause of amnesia? Because every time I look at you, I forget everything else.",
        "{}, Are you a great computer with a 4K monitor and the"
        " best graphics card ever? Because I just can't stop looking at you~",
        "{}, Are you a peanut butter? Coz i love peanut butter. Damn I love peanut butter",
        "{}, Are you a parking ticket? Because you have fine written all over you. :sunglasses:",
        "{}, Are you a sharpie? Because you're ultra fine.",
        "{}, you might be asked to leave soon. you're making the other women look bad.",
        "{}, are u Google? Cuz you're everything I'm searching for",
        "{}, There's a problem with my phone. your number isn't in it",
        "{}, Do you know what my shirt is made of? Boyfriend/girlfriend material",
        "{}, Are you australian? Because you meet all of my koalafications.",
        "{}, Hello. Cupid called. He wants to tell you that he needs my heart back.",
        "{}, You remind me of a magnet, because you sure are attracting me over here!",
        "{}, Hey, you’re pretty and I’m cute. Together we’d be Pretty Cute.",
        "{}, You must be a website, because im looking all over you",
        "{}, They say a kiss is the language of love. Wanna have a conversation?",
        "{}, Are you the rains down in Africa, because when I’m away from you I miss you",
        "If I had a lily for every thought I had of you, I would spend forever in my garden",
        "{}, Did you hear the voices sing? Cus my book of love just opened up and let you in.",
        "Hey {}, I’m lost. Can you give me directions to your heart?",
    ],
    "pat": [
        "{0} lightly pats {1} with a cute smile.",
        "{0} pats and scritches {1}'s head while giving them a treat.",
        "{1} happily nuzzles into {0}'s hand and bleps as {0} gives them lots of pats.",
        "{1} flops onto {0}'s lap for gentle adorable pats.",
        "{1} makes nonstop animal noises until {0} gives them pats.",
        "{0} looks over at {1}, who is rolling around and begging for pats.",
        "{0} gives {1} official pats of approval!",
        "{0} graces {1}'s head with gentle pats.",
        "{1} rolls over to {0} and gets some nice pats.",
        "{0} give {1} some pats to cheer them up.",
    ],
    "kills": [
        "{1} shoots  in {0}'s mouth with rainbow laser, causing "
        "{0}'s head to explode with rainbows and {0} is reborn as unicorn. :unicorn:",
        "{0} ate a piece of exotic butter. It was so amazing that it killed them.",
        "{0} is stuffed into a suit by Freddy on their night guard duty. Oh, not those animatronics again!",
        "{1} grabs {0} and shoves them into an auto-freeze machine "
        "with some juice and sets the temperature to 100 Kelvin, creating human ice pops.",
        '{1} drowns {0} in a tub of hot chocolate. *"How was your last drink?"*',
        "{0} screams in terror as they accidentally spawn in the cthulhu"
        " while uttering random latin words. Cthulhu grabs {0} by the right"
        " leg and takes them to his dimension yelling, 'Honey, Dinner's ready!'",
        "{1} feeds toothpaste-filled oreos to {0}, who were apparently allergic to fluorine. GGWP.",
        "{1} forgot to zombie-proof {0}'s lawn... Looks like zombies had a feast last night.",
        "{0} cranks up the music system only to realize the volume was at max"
        " and the song playing was Baby by Justin Beiber...",
        "{0} presses a random button and is teleported to the height of 100m,"
        " allowing them to fall to their inevitable death. Moral of the story:"
        " Don't go around pressing random buttons.",
        "{0} is injected with chocolate syrup, which mutates them into a person "
        "made out of chocolate. While doing a part-time job at the Daycare, they"
        " are devoured by the hungry babies. :chocolate_bar:",
        "{0} is sucked into Minecraft. {0}, being a noob at the "
        "so called 'Real-Life Minecraft' faces the Game Over screen.",
        "{1} turns on Goosebumps (2015 film) on the TV. {0} being a scaredy-cat, dies of a heart attack.",
        "{1} after a long day, plops down on the couch with {0} and turns on The"
        " Big Bang Theory. After a Sheldon Cooper joke, {0} laughs uncontrollably"
        " as they die.",
        "{0} was given a chance to synthesize element 119 (Ununennium) and have "
        "it named after them, but they messed up. R.I.P.",
        "{1} gets {0} to watch anime with them. {0} couldn't handle it.",
        "{0} tried to get crafty, but they accidentally cut themselves with the scissors.:scissors:",
        "{0} goes genocide and Sans totally dunks {0}!",
        "{1} was so swag that {0} died due to it. #Swag",
        "{0} has been found guilty, time for their execution!",
        "{0} fell down a cliff while playing Pokemon Go."
        " Good job on keeping your nose in that puny phone. :iphone:",
        "{1} strikes {0} with the killing curse... *'Avada Kedavra!'*",
        "{0} ate an apple and turned out it was made out of wax. Someone died from wax poisoning later that day.",
        "{0} was teleported to the timeline where Jurassic World "
        "was real and they were eaten alive by the Indominus Rex.",
        "{0} was charging their Samsung Galaxy Note 7...",
        "{1} shot {0} using the Starkiller Base!",
        "{0} was a resident of Alderaan before Darth Vader destroyed the planet...",
        "{0} was scooped by {1} and their innards are now Ennard.",
        "{1} Alt+F4'd {0}.exe!",
        "{0} was accused of stealing Neptune's crown...",
    ],
    "insults": [
        "Yo Mama so fat she sued Xbox 360 for guessing her weight.",
        "You're so fat that when you were diagnosed with a flesh eating bacteria - "
        "the doctors gave you 87 years to live.",
        "You're so fat you've got more chins than a Hong Kong phone book.",
        "Yo Mama so fat she's on both sides of the family.",
        "Yo Mama so fat that even Dora couldn't explore her.",
        "Yo Mama so fat that she doesn't need the internet; she's already world wide.",
        "You're so fat that when you farted you started global warming.",
        "You're so fat the back of your neck looks like a pack of hot-dogs.",
        "You're so fat that when you fell from your bed you fell from both sides.",
        'You\'re so fat when you get on the scale it says "To be continued."',
        'You\'re so fat when you go swimming the whales start singing "We Are Family".',
        "You're so fat when you stepped on the scale, Buzz Lightyear popped out and"
        " said 'To infinity and beyond!'",
        "You're so fat when you turn around, people throw you a welcome back party.",
        "You're so fat when you were in school you sat by everybody.",
        "You're so fat when you went to the circus the little girl asked if she could ride the elephant.",
        "You're so fat when you go on an airplane, you have to pay baggage fees for your ass.",
        "You're so fat whenever you go to the beach the tide comes in.",
        "You're so fat I could slap your butt and ride the waves.",
        "You're so fat I'd have to grease the door frame and hold a Twinkie on the"
        " other side just to get you through.",
        "Yo Mama so dumb I told her Christmas was around the corner and she went looking for it.",
        "You're so dumb it took you 2 hours to watch 60 minutes.",
        "Yo Mama so dumb she bought tickets to Xbox Live.",
        "You're so dumb that you thought The Exorcist was a workout video.",
        "You're so ugly that you went to the salon and it took 3 hours just to get an estimate.",
        "You're so ugly that even Scooby Doo couldn't solve that mystery.",
        "What is the weighted center between Planet X and Planet Y? Oh it's YOU!",
        ":eggplant: :eggplant: :eggplant:",
        ":cheese: :cheese: :cheese:",
        "Don't let your mind wander -- it's too little to be let out alone.",
        "Don't thank me for insulting you. It was my pleasure.",
        "Don't you realize that there are enough people to hate in the world "
        "already without you working so hard to give us another?",
        "Everyone is gifted. Some open the package sooner.",
        "Fat? You're not fat, you're just ... fat.",
        "Forgot to pay his brain bill.",
        "Grasp your ears firmly and remove your head from your ass.",
        "Has the IQ of lint.",
        "Talk is cheap, but so are you.",
        "has more faces than Mount Rushmore.",
        "has one brain cell, and it is fighting for dominance.",
        "is depriving a village somewhere of an idiot.",
        "is living proof that man can live without a brain!",
        "is so short his hair smell like feet",
        "is so old that their blood type was discontinued.",
        "Pardon me, but you've obviously mistaken me for someone who gives a damn.",
        "Did the mental hospital test too many drugs on you today?",
        "Don't get insulted, but is your job devoted to spreading ignorance?",
        "your birth certificate is an apology letter from the condom factory.",
        "I wasn't born with enough middle fingers to let you know how I feel about you.",
        "You must have been born on a highway because that's where most accidents happen.",
        "I'm jealous of all the people that haven't met you.",
        "I bet your brain feels as good as new, seeing that you never use it.",
        "I'm not saying I hate you, but I would unplug your life support to charge my phone.",
        "You're so ugly, when your mom dropped you off at school she got a fine for littering.",
        "You bring everyone a lot of joy, when you leave the room.",
        "You're as bright as a black hole, and twice as dense.",
        "I tried to see things from your perspective, but I couldn't seem to shove my head that far up my ass.",
        "Two wrongs don't make a right, take your parents as an example.",
        "You're the reason the gene pool needs a lifeguard.",
        "A guy with your IQ should have a low voice too!",
        "After meeting you, I've decided I am in favor of abortion in cases of incest.",
        "All of your ancestors must number in the millions; it's hard to believe that "
        "many people are to blame for producing you.",
        "I've seen people like you, but I had to pay admission!",
        "At least you are not obnoxious like so many other people - you are obnoxious in a different and worse way!",
        "Believe me, I don't want to make a monkey out of you. Why should I take all the credit?",
        "Brains aren't everything. In fact, in your case they're nothing!",
        "If laughter is the best medicine, your face must be curing the world.",
        "You're so ugly, when you popped out the doctor said 'Aww what a treasure' "
        "and your mom said 'Yeah, lets bury it.'",
        "I have neither the time nor the crayons to explain this to you.",
        "You have two brains cells, one is lost and the other is out looking for it.",
        "How many times do I have to flush to get rid of you?",
        "I don't exactly hate you, but if you were on fire and I had water, I'd drink it.",
        "You shouldn't play hide and seek, no one would look for you.",
        "Some drink from the fountain of knowledge; you only gargled.",
        "Roses are red violets are blue, God made me pretty, what happened to you?",
        "It's better to let someone think you are an Idiot than to open your mouth and prove it.",
        "Somewhere out there is a tree, tirelessly producing oxygen so you can breathe. "
        "I think you owe it an apology.",
        "The last time I saw a face like yours I fed it a banana.",
        "Which sexual position produces the ugliest children? Ask your mother.",
        "If you really want to know about mistakes, you should ask your parents.",
        "At least when I do a handstand my stomach doesn't hit me in the face.",
        "If I gave you a penny for your thoughts, I'd get change.",
        "If I were to slap you, it would be considered animal abuse.",
        "Do you know how long it takes for your mother to take a crap? Nine months.",
        "What are you going to do for a face when the baboon wants his butt back?",
        "Well I could agree with you, but then we'd both be wrong.",
        "You're so fat, you could sell shade.",
        "It looks like your face caught on fire and someone tried to put it out with a hammer.",
        "You're not funny, but your life, now that's a joke.",
        "You're so fat the only letters of the alphabet you know are KFC.",
        "Oh my god, look at you. Was anyone else hurt in the accident?",
        "What are you doing here? Did someone leave your cage open?",
        "You're so ugly, the only dates you get are on a calendar.",
        "I can explain it to you, but I can't understand it for you.",
        "You are proof that God has a sense of humor.",
        "If you spoke your mind, you'd be speechless.",
        "Why don't you check eBay and see if they have a life for sale.",
        "If I wanted to hear from an asshole, I'd fart.",
        "You're so fat you need cheat codes to play Wii Fit",
        "You're so ugly, when you got robbed, the robbers made you wear their masks.",
        "Do you still love nature, despite what it did to you?",
        "You are proof that evolution CAN go in reverse.",
        "I'll never forget the first time we met, although I'll keep trying.",
        "Your parents hated you so much your bath toys were an iron and a toaster",
        "Don't feel sad, don't feel blue, Frankenstein was ugly too.",
        "You're so ugly, you scared the crap out of the toilet.",
        "It's kinda sad watching you attempt to fit your entire vocabulary into a sentence.",
        "I fart to make you smell better.",
        "You're so ugly you make blind kids cry.",
        "You're a person of rare intelligence. It's rare when you show any.",
        "You're so fat, when you wear a yellow rain coat people scream ''taxi''.",
        "I heard you went to a haunted house and they offered you a job.",
        "You look like a before picture.",
        "If your brain was made of chocolate, it wouldn't fill an M&M.",
        "Aww, it's so cute when you try to talk about things you don't understand.",
        "I heard your parents took you to a dog show and you won.",
        "You stare at frozen juice cans because they say, 'concentrate'.",
        "You're so stupid you tried to wake a sleeping bag.",
        "Am I getting smart with you? How would you know?",
        "We all sprang from apes, but you didn't spring far enough.",
        "I'm no proctologist, but I know an asshole when I see one.",
        "When was the last time you could see your whole body in the mirror?",
        "You must have a very low opinion of people if you think they are your equals.",
        "So, a thought crossed your mind? Must have been a long and lonely journey.",
        "You're the best at all you do - and all you do is make people hate you.",
        "Looks like you fell off the ugly tree and hit every branch on the way down.",
        "Looks aren't everything; in your case, they aren't anything.",
        "You have enough fat to make another human.",
        "You're so ugly, when you threw a boomerang it didn't come back.",
        "You're so fat a picture of you would fall off the wall!",
        "Your hockey team made you goalie so you'd have to wear a mask.",
        "Ordinarily people live and learn. You just live.",
        "Did your parents ever ask you to run away from home?",
        "I heard you took an IQ test and they said your results were negative.",
        "You're so ugly, you had tinted windows on your incubator.",
        "Don't you need a license to be that ugly?",
        "I'm not saying you're fat, but it looks like you were poured"
        " into your clothes and someone forgot to say 'when'",
        "I've seen people like you, but I had to pay admission!",
        "I hear the only place You're ever invited is outside.",
        "Keep talking, someday you'll say something intelligent!",
        "You couldn't pour water out of a boot if the instructions were on the heel.",
        "Even if you were twice as smart, you'd still be stupid!",
        "You're so fat, you have to use a mattress as a maxi-pad.",
        "I may be fat, but You're ugly, and I can lose weight.",
        "I was pro life before I met you.",
        "What's the difference between you and Hitler? Hitler knew when to kill himself.",
        "You're so fat, your double chin has a double chin.",
        "If ignorance is bliss, you must be the happiest person on earth.",
        "You're so stupid, it takes you an hour to cook minute rice.",
        "Is that your face? Or did your neck just throw up?",
        "You're so ugly you have to trick or treat over the phone.",
        "I'd hit you but we don't hit girls around here.",
        "Dumbass.",
        "Bitch.",
        "Retard.",
        "I'd give you a nasty look but you've already got one.",
        "If I wanted a bitch, I'd have bought a dog.",
        "Scientists say the universe is made up of neutrons, protons and electrons. They forgot to mention morons.",
        "Why is it acceptable for you to be an idiot but not for me to point it out?",
        "Did you know they used to be called 'Jumpolines' until your mum jumped on one?",
        "You're not stupid; you just have bad luck when thinking.",
        "I thought of you today. It reminded me to take the garbage out.",
        "I'm sorry I didn't get that - I don't speak idiot.",
        "Hey, your village called \u2013 they want their idiot back.",
        "I just stepped in something that was smarter than you\u2026 and smelled better too.",
        "You're so fat that at the zoo the elephants started throwing you peanuts.",
        "You're so fat every time you turn around, it's your birthday.",
        "You're so fat your idea of dieting is deleting the cookies from your internet cache.",
        "You're so fat your shadow weighs 35 pounds.",
        "You're so fat I could tell you to haul ass and you'd have to make two trips.",
        "You're so fat I took a picture of you at Christmas and it's still printing.",
        "You're so fat I tried to hang a picture of you on my wall, and my wall fell over.",
        "You're so fat Mount Everest tried to climb you.",
        "You're so fat you can't even jump to a conclusion.",
        "You're so fat you can't fit in any timeline.",
        "You're so fat you can't fit in this joke.",
        "You're so fat you don't skinny dip, you chunky dunk.",
        "You're so fat you fell in love and broke it.",
        "You're so fat you go to KFC and lick other peoples' fingers.",
        "You're so fat you got arrested at the airport for ten pounds of crack.",
        "You're so fat you'd have to go to Sea World to get baptized.",
        "You're so fat you have your own zip code.",
        "You're so fat you have more rolls than a bakery.",
        "You're so fat you don't have got cellulite, you've got celluheavy.",
        "You're so fat you influence the tides.",
        "You're so fat you jumped off the Grand Canyon and got stuck.",
        "You're so fat that you laid on the beach and Greenpeace tried to push you back in the water.",
        "You're so fat you leave footprints in concrete.",
        "You're so fat you need GPS to find your asshole.",
        "You're so fat you pull your pants down and your ass is still in them.",
        "You're so fat you show up on radar.",
        "If you were any less intelligent we'd have to water you three times a week..",
        "If your IQ was 3 points higher, you'd be a rock.",
        "I would insult you but nature did a better job.",
        "Does your ass get jealous of all the shit that comes out of your mouth?",
        "If I ate a bowl of alphabet soup, I could shit out a smarter sentence than any of yours.",
        "You're not pretty enough to be this stupid.",
        "That little voice in the back of your head, telling you you'll never be good enough? It's right.",
        "You look like you're going to spend your life having one epiphany after another, "
        "always thinking you've finally figured out what's holding you back, and how you can"
        " finally be productive and creative and turn your life around. But nothing will"
        " ever change. That cycle of mediocrity isn't due to some obstacle. It's who you *are*."
        " The thing standing in the way of your dreams is; that the person having them is *you*.",
        "May your day and future be as pleasant as you are.",
        "I would agree with you but then we would both be wrong.",
        "I bite my thumb at you, sir.",
        "I'd call you a tool, but that would imply you were useful in at least one way.",
        "I hope you outlive your children.",
        "Yo mama is so ugly her portraits hang themselves.",
        "Your birth certificate is an apology from the abortion clinic.",
        "If you were any more inbred you'd be a sandwich.",
    ]
}


@dataclass
class SocialLines:

    @staticmethod
    def get_social_line(line: str, is_nsfw: bool = False):
        if is_nsfw:
            line = nsfw[line]
            line_choice = randomization.advchoice(line)
            return line_choice
        else:
            line = sfw[line]
            line_choice = randomization.advchoice(line)
            return line_choice
