roles_NSFW = [
    "Male",
    "Female",
    "Agender",
    "Genderfluid",
    "Transgender",
    "Agender",
    "Asexual",
    "Bisexual",
    "Gay",
    "Lesbian",
    "Pansexual",
    "Straight",
    "Aromantic",
    "Taken",
    "Single",
    "Mention",
    "No Mention",
    "18+",
    "Underage",
    "Registered",
    "Dominant",
    "Submissive",
    "Switch",
    "DMs NOT Allowed",
    "DMs Allowed",
    "Ask to DM",
    "Seeking for partner",
    "Not seeking for partner",
    "NSFW",
]
